### ISSUE TITLE
跨卡切分共享GPU显存和算力

### ISSUE THREAD

**Issue by czh1985** [Project-HAMi/HAMi#121]
公司: 中国电子
集群规模:3节点
使用场景:进行GPU的虚拟化并使用k8s调度GPU资源
显卡型号:NVIDIA-Quadro 4090*8
   
 感谢开源实属不容易啊！
  能否池化GPU比如一个node有8张卡，现只能单卡多实例运行容器，能否支持多卡共享显存，提高资源利用率，比如一张卡资源耗尽，另一张空闲卡可以共享显存和算力，一个任务一个pod,每个pod使用12G显存，这样1 2 pod会用第一张卡，3 4 pod用第二张卡

**Comment by luli817** [comment]
我也有这个需求，请问你解决了吗？
