### ISSUE TITLE
虚拟显存及算力超卖问题

### ISSUE THREAD

**Issue by geekidentity** [Project-HAMi/HAMi#15]
1. 虚拟显存的使用对操作系统有要求吗，是否必须使用OpenAIOS。
2. 未来有打算支持GPU算力超卖的计划吗。

**Comment by archlitchi** [comment]
1. 对操作系统没有要求，只要是k8s v1.14以上的版本就可以
2. 有的

**Comment by geekidentity** [comment]
请问GPU算力超卖咱这边是已经有计划了，还是在规划中呢。

**Comment by archlitchi** [comment]
有计划，但我不确定我和你理解的GPU算力超卖是不是一回事，方便的话可以去slack上详细交流一下，或者加我wx：xuanzong4493
