### ISSUE TITLE
非root用户算力无法隔离，无法查看分配资源

### ISSUE THREAD

**Issue by JJwangbilin** [Project-HAMi/HAMi#16]
**现象：**
非root用户进入容器中，无法查看分配的mem-limit资源，nvidia-smi看到的内容和宿主机上的内容完全一样。
**解决方法**
需修改宿主机/usr/local/vgpu/下文件的权限。
chmod 777 /usr/local/vgpu/*
**问题**
以普通用户进入容器，执行nvidia-smi，结果如下：
Fail to open shrreg /tmp/vgpu/vudevshr/cache:errno=13
nvidia-smi: /home/limengxuan/work/libcuda_override/src/multiprocess/multiprocess_memory_limit.c:504: try_create_shrreg:Assertion '0' failed
Aborted (core dumped)

切换到root用户执行一次nvidia-smi，再切回普通用户就正常可用了。

**期望**
希望普通用户可正常使用nvidia-smi

**Comment by rnyrnyrny** [comment]
我们也遇到这个问题，目前是改代码把CUDA_DEVICE_MEMORY_SHARED_CACHE改成/tmp/cudevshr.cache来规避

**Comment by JJwangbilin** [comment]
> 我们也遇到这个问题，目前是改代码把CUDA_DEVICE_MEMORY_SHARED_CACHE改成/tmp/cudevshr.cache来规避

改算法的代码吗？还是改vgpu-scheduler？

**Comment by rnyrnyrny** [comment]
> > 我们也遇到这个问题，目前是改代码把CUDA_DEVICE_MEMORY_SHARED_CACHE改成/tmp/cudevshr.cache来规避
> 
> 改算法的代码吗？还是改vgpu-scheduler？

改[这里](https://github.com/4paradigm/k8s-vgpu-scheduler/blob/master/cmd/nvidia-container-runtime/nvcr.go#L192)，可以看下我之前提的issue #12 ，最后写了我想的修改方法

**Comment by AntyRia** [comment]
这个要在内核态执行切割吧 操作要root权限
