### ISSUE TITLE
部署成功之后集群内都不能新建pod了，报错failed calling webhook

### ISSUE THREAD

**Issue by luli817** [Project-HAMi/HAMi#160]
集群版本1.26.9
<img width="755" alt="image" src="https://github.com/Project-HAMi/HAMi/assets/31745402/c7147b36-30d5-4c66-8116-ac08eff0cbc1">

![image](https://github.com/Project-HAMi/HAMi/assets/31745402/2f1fd621-203a-4cdf-966d-1806607dac1b)
![image](https://github.com/Project-HAMi/HAMi/assets/31745402/8c90f429-128a-43b8-9847-3bd3038b65c3)

**Comment by chaunceyjiang** [comment]
Can you share your `webhook configuration` and the `svc` information under the `kube-system` namespace?

**Comment by chaunceyjiang** [comment]
Everything seems fine, is your k8s cluster working normally? You can further check if the network of the cluster is working properly.

**Comment by luli817** [comment]
![image](https://github.com/Project-HAMi/HAMi/assets/31745402/c8650d1d-1435-434d-b3b1-030239fcf3ee)

**Comment by luli817** [comment]
I have checked the cluster network, host network, service network, Kube Proxy, and Cilium CNI, all of which are normal

**Comment by luli817** [comment]
能加你微信或者钉钉吗？我好像已经定位到原因了

**Comment by FAYEMOU** [comment]
请问这个问题，怎么解决的呢？我也遇到了同样的情况，所有的组件看起来都正常，但是就是有Failed calling webhook, failing open vgpu.hami.io: failed calling webhook "vgpu.hami.io": failed to call webhook: Post "https://hami-scheduler.kube-system.svc:443/webhook?timeout=30s": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
E0707 11:53:33.346585       1 dispatcher.go:180] failed calling webhook "vgpu.hami.io": failed to call webhook: Post "https://hami-scheduler.kube-system.svc:443/webhook?timeout=30s": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

**Comment by FAYEMOU** [comment]
> 请问这个问题，怎么解决的呢？我也遇到了同样的情况，所有的组件看起来都正常，但是就是有Failed calling webhook, failing open vgpu.hami.io: failed calling webhook "vgpu.hami.io": failed to call webhook: Post "https://hami-scheduler.kube-system.svc:443/webhook?timeout=30s": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers) E0707 11:53:33.346585 1 dispatcher.go:180] failed calling webhook "vgpu.hami.io": failed to call webhook: Post "https://hami-scheduler.kube-system.svc:443/webhook?timeout=30s": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

@luli817 @chaunceyjiang

**Comment by luli817** [comment]
当时解决了后面就忘记了
