### ISSUE TITLE
【问题】device-plugin的容器异常重启

### ISSUE THREAD

**Issue by TymonLee** [Project-HAMi/HAMi#169]
我们集群4090节点上的device-plugin容器有时候会异常退出重启，目前还没有定位到触发条件是什么
查看Pod的容器状态，看到 Exit Code 为 1
![image](https://github.com/Project-HAMi/HAMi/assets/23135265/88000a72-1011-486a-9c6c-5a2cef1cfe55)

查看device-plugin容器的日志只能看到 cmd.Run() 255异常退出的日志
```
I0301 09:05:40.556765 1132064 register.go:113] Reporting devices GPU-88dadc4b-c5f2-3d01-4b4c-7dfc09bd1ae7,10,24576,100,NVIDIA-NVIDIA GeForce RTX 3090,0,false:GPU-458b6298-2798-a9da-8059-821ed05edc66,10,24576,100,NVIDIA-NVIDIA GeForce RTX 3090,0,false:GPU-6d9c8df4-1f93-ed41-822b-127c1086dc82,10,24576,100,NVIDIA-NVIDIA GeForce RTX 3090,0,false:GPU-2185c99e-17ab-824c-1010-d28b07115ce2,10,24576,100,NVIDIA-NVIDIA GeForce RTX 3090,0,false:GPU-abb12640-42ef-e136-38ea-d27e10446287,10,24576,100,NVIDIA-NVIDIA GeForce RTX 3090,0,false:GPU-e3b4d076-f9a2-5fd1-0791-4da6c6c7aa5f,10,24576,100,NVIDIA-NVIDIA GeForce RTX 3090,0,false:GPU-7f18c6e7-6b53-f22e-4a34-54383576c91f,10,24576,100,NVIDIA-NVIDIA GeForce RTX 3090,0,false:GPU-b20a9486-d172-46e0-9883-d5280d95d583,10,24576,100,NVIDIA-NVIDIA GeForce RTX 3090,0,false: in 2024-03-01 09:05:40.556752107 +0000 UTC m=+1871.551534314
I0301 09:05:41.172863 1132064 util.go:179] pdevices= [[{0 GPU-b20a9486-d172-46e0-9883-d5280d95d583 NVIDIA 8192 0}]]
I0301 09:05:41.172913 1132064 server.go:315] deviceAllocateFromAnnotation= [{0 GPU-b20a9486-d172-46e0-9883-d5280d95d583 NVIDIA 8192 0}]
I0301 09:05:41.172928 1132064 util.go:218] Selecting erase res= NVIDIA : NVIDIA
Encoded container Devices= 
I0301 09:05:41.172931 1132064 util.go:232] After erase res= [[]]
I0301 09:05:41.185176 1132064 server.go:400] Allocate Response [&ContainerAllocateResponse{Envs:map[string]string{CUDA_DEVICE_MEMORY_LIMIT_0: 8192m,CUDA_DEVICE_MEMORY_SHARED_CACHE: /usr/local/vgpu/d75b31b5-4f1c-48e5-9ed5-e35e92f0dd41.cache,CUDA_DEVICE_SM_LIMIT: 0,NVIDIA_VISIBLE_DEVICES: GPU-b20a9486-d172-46e0-9883-d5280d95d583,},Mounts:[]*Mount{&Mount{ContainerPath:/usr/local/vgpu/libvgpu.so,HostPath:/usr/local/vgpu/libvgpu.so,ReadOnly:true,},&Mount{ContainerPath:/usr/local/vgpu,HostPath:/usr/local/vgpu/containers/39675db4-7860-4a30-8fa0-4e25b6bb3f5e_offboard-prediction-bag-d0240301-170523-a0ad25a107,ReadOnly:false,},&Mount{ContainerPath:/tmp/vgpulock,HostPath:/tmp/vgpulock,ReadOnly:false,},&Mount{ContainerPath:/etc/ld.so.preload,HostPath:/usr/local/vgpu/ld.so.preload,ReadOnly:true,},},Devices:[]*DeviceSpec{},Annotations:map[string]string{},}]
I0301 09:05:41.195824 1132064 devices.go:57] TrySuccess: 
I0301 09:05:41.195836 1132064 devices.go:63] AllDevicesAllocateSuccess releasing lock
I0301 09:05:41.231202 1132064 nodelock.go:77] "Node lock released" node="10-3-8-71.bm.pd.sz.deeproute.ai"
2024/03/01 09:06:10 cmd.Run() failed with exit status 255
```
想问下可能是什么原因？

**Comment by lengrongfu** [comment]
@TymonLee can you provide Nvidia driver version info and cuda version info.

**Comment by TymonLee** [comment]
> @TymonLee can you provide Nvidia driver version info and cuda version info.

Nvidia driver version: e6c111af
cuda version: 12.2

**Comment by TymonLee** [comment]
> @TymonLee can you provide Nvidia driver version info and cuda version info.

As the picture posted above:  Driver Version: 535.129.03   CUDA Version: 12.2

I was suspecting this block of code:

> func (plugin *NvidiaDevicePlugin) getNumaInformation(idx int) (int, error) {
> 	cmd := exec.Command("nvidia-smi", "topo", "-m")
> 	out, err := cmd.CombinedOutput()
> 	if err != nil {
> 		log.Fatalf("cmd.Run() failed with %s\n", err)
> 	}

Maybe there is no need to panic? Returning an error to previous function call is enough?

**Comment by wawa0210** [comment]
> > @TymonLee can you provide Nvidia driver version info and cuda version info.
> 
> As the picture posted above: Driver Version: 535.129.03 CUDA Version: 12.2
> 
> I was suspecting this block of code:
> 
> > func (plugin *NvidiaDevicePlugin) getNumaInformation(idx int) (int, error) {
> > cmd := exec.Command("nvidia-smi", "topo", "-m")
> > out, err := cmd.CombinedOutput()
> > if err != nil {
> > log.Fatalf("cmd.Run() failed with %s\n", err)
> > }
> 
> Maybe there is no need to panic? Returning an error to previous function call is enough?

Very interesting. Normally `nvidia-smi topo -m` should be executed without error. What is the error message when executed on your node? Can you upload it?

**Comment by wawa0210** [comment]
> > Can this issue be reproduced? There are no abnormalities found in the code and logs.
> 
> 从代码中看应该是执行"nvidia-smi topo -m"这条命令的时候出错，但是我手动进device-plugin和业务容器执行这条命令都是成功的。倒是执行"nvidia-smi"的时候有以下报错，不知道是否有关： ![image](https://private-user-images.githubusercontent.com/23135265/310768120-715b1b00-3e3b-4e90-88a9-02b7fd948bee.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQyODU0OTEsIm5iZiI6MTcxNDI4NTE5MSwicGF0aCI6Ii8yMzEzNTI2NS8zMTA3NjgxMjAtNzE1YjFiMDAtM2UzYi00ZTkwLTg4YTktMDJiN2ZkOTQ4YmVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI4VDA2MTk1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJjZThjZTI5ZGFmYmUwZTc4ZTRmMDY0Mjg1NWE4NGU2YTdhMWJkNzQwMDg4ZjFhZDk2NDQ3MDJjMWZmNGIyNWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QkoNfdtLDQBo6bHDxXmZHsHnDhHjdDHhNUiSwLN_-OQ)

Very interesting. Normally `nvidia-smi topo -m` should be executed without error. What is the error message when executed on your node? Can you upload it?

**Comment by wawa0210** [comment]
> > @TymonLee can you provide Nvidia driver version info and cuda version info.
> 
> As the picture posted above: Driver Version: 535.129.03 CUDA Version: 12.2
> 
> I was suspecting this block of code:
> 
> > func (plugin *NvidiaDevicePlugin) getNumaInformation(idx int) (int, error) {
> > cmd := exec.Command("nvidia-smi", "topo", "-m")
> > out, err := cmd.CombinedOutput()
> > if err != nil {
> > log.Fatalf("cmd.Run() failed with %s\n", err)
> > }
> 
> Maybe there is no need to panic? Returning an error to previous function call is enough?

It is really unreasonable to panic and exit directly. You should just output the error log.

**Comment by TymonLee** [comment]
> > > @TymonLee can you provide Nvidia driver version info and cuda version info.
> > 
> > 
> > As the picture posted above: Driver Version: 535.129.03 CUDA Version: 12.2
> > I was suspecting this block of code:
> > > func (plugin *NvidiaDevicePlugin) getNumaInformation(idx int) (int, error) {
> > > cmd := exec.Command("nvidia-smi", "topo", "-m")
> > > out, err := cmd.CombinedOutput()
> > > if err != nil {
> > > log.Fatalf("cmd.Run() failed with %s\n", err)
> > > }
> > 
> > 
> > Maybe there is no need to panic? Returning an error to previous function call is enough?
> 
> It is really unreasonable to panic and exit directly. You should just output the error log.

The error code is `255` and the output is `Unknown error`. Maybe many users' pods are also executing `nvidia-smi` at the same time and that caused some errors related to concurrency? There are a lot of user pods on a single machine. And this is an occasional error.
