### ISSUE TITLE
【问题】如何本地编译运行HAMi

### ISSUE THREAD

**Issue by Hapluckyy** [Project-HAMi/HAMi#174]
我想通过docker 本地编译运行该项目，请问编译的流程是什么，我需要什么环境准备？

**Comment by Hapluckyy** [comment]
我在直接运行dockerfile时遇到了以下错误，请问这两个变量需要进行什么操作？
```
(base) [root@node2 docker]# docker build -f Dockerfile .
[+] Building 0.0s (1/1) FINISHED                                                        docker:default
 => [internal] load build definition from Dockerfile                                              0.0s
 => => transferring dockerfile: 1.37kB                                                            0.0s
Dockerfile:3
--------------------
   1 |     ARG GOLANG_IMAGE
   2 |     ARG NVIDIA_IMAGE
   3 | >>> FROM $GOLANG_IMAGE AS build
   4 |     
   5 |     FROM $GOLANG_IMAGE AS GOBUILD
--------------------
ERROR: failed to solve: base name ($GOLANG_IMAGE) should not be blank
```

**Comment by wawa0210** [comment]
> 我在直接运行dockerfile时遇到了以下错误，请问这两个变量需要进行什么操作？
> 
> ```
> (base) [root@node2 docker]# docker build -f Dockerfile .
> [+] Building 0.0s (1/1) FINISHED                                                        docker:default
>  => [internal] load build definition from Dockerfile                                              0.0s
>  => => transferring dockerfile: 1.37kB                                                            0.0s
> Dockerfile:3
> --------------------
>    1 |     ARG GOLANG_IMAGE
>    2 |     ARG NVIDIA_IMAGE
>    3 | >>> FROM $GOLANG_IMAGE AS build
>    4 |     
>    5 |     FROM $GOLANG_IMAGE AS GOBUILD
> --------------------
> ERROR: failed to solve: base name ($GOLANG_IMAGE) should not be blank
> ```

if we want to make images, You can execute this command `make docker`
