### ISSUE TITLE
默认情况下，pod 是独占整张 GPU 卡显存的吗？

### ISSUE THREAD

**Issue by 2232729885** [Project-HAMi/HAMi#194]
我使用如下的命令安装 hami，不带参数“scheduler.defaultMem”
helm install hami hami-charts/hami \
  -n kube-system \
  --set scheduler.kubeScheduler.imageTag=v1.27.2 \
  --set devicePlugin.deviceSplitCount=5 \
  --set devicePlugin.migstrategy=none \
  --set scheduler.defaultCores=0 \
  --set scheduler.defaultGPUNum=1 \
  --set resourceName=nvidia.com/gpu \
  --set resourceMem=nvidia.com/gpumem \
  --set resourceMemPercentage=nvidia.com/gpumem-percentage \
  --set resourceCores=nvidia.com/cores \
  --set resourcePriority=nvidia.com/priority \
  --set devicePlugin.tolerations[0].key=nvidia.com/gpu \
  --set devicePlugin.tolerations[0].operator=Exists \
  --set devicePlugin.tolerations[0].effect=NoSchedule

然后启动一个pod，申请6个vgpu，不指定“nvidia.com/gpumem”：

apiVersion: v1
kind: Pod
metadata:
  namespace: algorithm-platform
  name: gpu-pod
spec:
  tolerations:
    - key: nvidia.com/gpu
      operator: Exists
      effect: NoSchedule
  containers:
    - name: ubuntu-container
      image: ubuntu:18.04
      command: ["bash", "-c", "sleep 86400"]
      resources:
        limits:
          nvidia.com/gpu: 6 # requesting 2 vGPUs

pod可以正常调度到 gpu 节点，vpu-scheduler 日志显示：
![image](https://github.com/Project-HAMi/HAMi/assets/138634190/26c73e16-1bcf-402d-81dd-b090b5d8738f)

然后我只修改pod 名字，又启动一个pod：
apiVersion: v1
kind: Pod
metadata:
  namespace: algorithm-platform
  name: gpu-pod-1
spec:
  tolerations:
    - key: nvidia.com/gpu
      operator: Exists
      effect: NoSchedule
  containers:
    - name: ubuntu-container
      image: ubuntu:18.04
      command: ["bash", "-c", "sleep 86400"]
      resources:
        limits:
          nvidia.com/gpu: 6 # requesting 2 vGPUs
pod 却无法调度，vpu-scheduler 日志显示如下，从日志推测，之前的 pod ，申请了6个 vgpu，每个vgpu用掉显存 ‘Usedmem’为A40卡的全部显存（独占整卡显存）；所以后来一个 pod 在计算 score 时，认为已分给上个 pod 的6张卡可用显存不满足新 Pod 调度需求
![image](https://github.com/Project-HAMi/HAMi/assets/138634190/9f1101cf-ad16-4f3a-a247-3cc0e27096d3)

但是从 readme 文档来看，我的 gpu 节点共有 8 张 A40，helm 安装时设置了参数 ‘devicePlugin.deviceSplitCount=5’，vgpu 资源总共有 40，这两个 pod 应该都是可以正常调度的才对

**Comment by 2232729885** [comment]
然后我又重新了安装了hami，加上了参数“scheduler.defaultMem=6000”，
“
helm install hami hami-charts/hami \
  -n kube-system \
  --set scheduler.kubeScheduler.imageTag=v1.27.2 \
  --set devicePlugin.deviceSplitCount=5 \
  --set devicePlugin.migstrategy=none \
  --set scheduler.defaultMem=6000 \
  --set scheduler.defaultCores=0 \
  --set scheduler.defaultGPUNum=1 \
  --set resourceName=nvidia.com/gpu \
  --set resourceMem=nvidia.com/gpumem \
  --set resourceMemPercentage=nvidia.com/gpumem-percentage \
  --set resourceCores=nvidia.com/cores \
  --set resourcePriority=nvidia.com/priority \
  --set devicePlugin.tolerations[0].key=nvidia.com/gpu \
  --set devicePlugin.tolerations[0].operator=Exists \
  --set devicePlugin.tolerations[0].effect=NoSchedule 
”
又创建了如上两个pod，发现两个pod都能正常调度，第二个pod启动时，vgpu-scheduler的日志显示：
![image](https://github.com/Project-HAMi/HAMi/assets/138634190/75c067ec-340e-45da-8146-d4935f21f596)
可以看到，其中6个gpu卡，每张已用显存为 6000m，即6G, 所以在计算score时，调度器认为这 6 张卡仍然满足pod需求

**Comment by lengrongfu** [comment]
if not set `defaultMem` then use all memory.

**Comment by 2232729885** [comment]
> if not set `defaultMem` then use all memory.

所以如果要多个Pod共享一张GPU卡，光设置devicePlugin.deviceSplitCount参数不行，还得要设置scheduler.defaultMem，若是这样的话，麻烦在 Readme 里面说明一下

**Comment by 2232729885** [comment]
> if not set `defaultMem` then use all memory.

如果helm 安装chart时不设置 scheduler.defaultMem，而是创建pod，指定容器资源的'nvidia.com/gpumem'参数，是不是也可以做到多pod共享同一张GPU卡？

**Comment by 2232729885** [comment]
> > if not set `defaultMem` then use all memory.
> 
> 如果helm 安装chart时不设置 scheduler.defaultMem，而是创建pod，指定容器资源的'nvidia.com/gpumem'参数，是不是也可以做到多pod共享同一张GPU卡？

这种方式我试验了下，也是可以实现 多pod共享同一张GPU卡的，结论就是，如果要实现多pod共享同一张GPU卡，有两种方式，一是 helm install 时指定参数 ‘scheduler.defaultMem’；二是在PodSpec的resources.limits中，显式指定‘nvidia.com/gpumem’；否则，pod容器内可见的将会是整张GPU的显存，也会独占所有显存，该卡将无法被分配给其它pod

**Comment by lengrongfu** [comment]
can you submit a pr to change `REAMD.md` and `README-cn.md`.

**Comment by lengrongfu** [comment]
> > if not set `defaultMem` then use all memory.
> 
> 如果helm 安装chart时不设置 scheduler.defaultMem，而是创建pod，指定容器资源的'nvidia.com/gpumem'参数，是不是也可以做到多pod共享同一张GPU卡？

yes, when in pod resource set `nvidia.com/gpumem` or `nvidia.com/gpucors`, scheduler will not use default values from  `scheduler.defaultMem` and `scheduler.defaultCore`.
