### ISSUE TITLE
ubuntu container with vGPU cannot start

### ISSUE THREAD

**Issue by umberto10** [Project-HAMi/HAMi#20]
Container with vgpu cannot start because of the following error:
`nvidia-smi: symbol lookup error: /usr/local/vgpu/libvgpu.so: undefined symbol: _dl_sym, version GLIBC_PRIVATE`

The pod running under the k8s-device-plugin from Nvidia works well.

pods with nvidia images works well. I wanted to build my own from scratch, but seems that ubuntu image (which I picked from your example) is not enough :/

no errors in logs of vgpu pods.

reproduce:
k8s version: v1.21.9 (RKE)
glibc:
<pre>
[root@wn0123 ~]# rpm -qa |grep glibc
glibc-headers-2.28-164.el8_5.3.x86_64
glibc-langpack-en-2.28-164.el8_5.3.x86_64
glibc-devel-2.28-164.el8_5.3.x86_64
glibc-2.28-164.el8_5.3.x86_64
glibc-common-2.28-164.el8_5.3.x86_64
</pre>

nvidia-drivers:
<pre>
[root@wn0123 ~]# rpm -qa |grep -i nvidia
nvidia-xconfig-510.47.03-1.el8.x86_64
nvidia-driver-libs-510.47.03-1.el8.x86_64
nvidia-fs-2.11.0-1.x86_64
nvidia-gds-11.6.2-1.x86_64
nvidia-persistenced-510.47.03-1.el8.x86_64
nvidia-modprobe-510.47.03-1.el8.x86_64
nvidia-fs-dkms-2.11.0-1.x86_64
nvidia-gds-11-6-11.6.2-1.x86_64
nvidia-container-toolkit-1.9.0-1.x86_64
nvidia-libXNVCtrl-510.47.03-1.el8.x86_64
nvidia-driver-cuda-510.47.03-1.el8.x86_64
kmod-nvidia-latest-dkms-510.47.03-1.el8.x86_64
nvidia-driver-510.47.03-1.el8.x86_64
libnvidia-container-tools-1.9.0-1.x86_64
nvidia-driver-NVML-510.47.03-1.el8.x86_64
nvidia-libXNVCtrl-devel-510.47.03-1.el8.x86_64
nvidia-kmod-common-510.47.03-1.el8.noarch
libnvidia-container1-1.9.0-1.x86_64
nvidia-driver-NvFBCOpenGL-510.47.03-1.el8.x86_64
nvidia-settings-510.47.03-1.el8.x86_64
nvidia-docker2-2.10.0-1.noarch
nvidia-driver-cuda-libs-510.47.03-1.el8.x86_64
dnf-plugin-nvidia-2.0-1.el8.noarch
nvidia-driver-devel-510.47.03-1.el8.x86_64
</pre>

pod.yaml:
<pre>
apiVersion: v1
kind: Pod
metadata:
  name: gpu-pod
spec:
  restartPolicy: Never
  containers:
    - name: test-container
      image: ubuntu:latest
      command: ["nvidia-smi"]
      env:
        - name: NVIDIA_VISIBLE_DEVICES
          value: all
        - name: NVIDIA_DRIVER_CAPABILITIES
          value: "compute,utility"
      securityContext:
        privileged: true
      resources:
        limits:
          nvidia.com/gpu: 1
          nvidia.com/gpumem: 3000 
          nvidia.com/gpucores: 30 
</pre>

Can you provide the correct way how sholud I build nvidia container from scratch that works with your plugin?

**Comment by OverdueCEO** [comment]
I have exactly the same error when using container images which have `glibc` version greater than `2.31`

**Comment by archlitchi** [comment]
Thanks for your issue, the same error occurs when your glibc in image is greater than 2.28, we are working on it

**Comment by archlitchi** [comment]
Thanks for your issue, the same error occurs when your glibc in image is greater than 2.28, we are working on it

**Comment by archlitchi** [comment]
fixed, please update to latest version

**Comment by umberto10** [comment]
Is this correct output from nvidia-smi?
as limits I've used only `nvidia.com/gpu: 1`

<pre>
[root@gpu-pod1 /]# nvidia-smi
[4pdvGPU Msg(357:140582650103616:libvgpu.c:826)]: Initializing...
[4pdvGPU Warn(357:140582650103616:multiprocess_memory_limit.c:544)]: size_t size=280392
merge pid=2455856[4pdvGPU Msg(357:140582650103616:context.c:120)]: vdevices_pci=0000:af:00.0
[4pdvGPU Msg(357:140582650103616:libvgpu.c:843)]: Initialized
[4pdvGPU Msg(357:140582650103616:multiprocess_utilization_watcher.c:205)]: into utilization_watcher 10

Tue May 17 07:56:24 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 510.47.03    Driver Version: 510.47.03    CUDA Version: 11.6     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla P100-PCIE...  Off  | 00000000:AF:00.0 Off |                    0 |
| N/A   38C    P0    32W / 250W |    253MiB / 16384MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A   2454099      C                                     253MiB |
|    0   N/A  N/A   2455856      C                                     253MiB |
+-----------------------------------------------------------------------------+
</pre>

**Comment by archlitchi** [comment]
what's the output of nvidia-smi outside container? Is it 253Mb or more?

**Comment by umberto10** [comment]
same 253M, but it never rises
and the GPU watts stays at the same level too.

<pre>
[root@wn0123 ~]# nvidia-smi
Tue May 17 06:04:48 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 510.47.03    Driver Version: 510.47.03    CUDA Version: 11.6     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla P100-PCIE...  Off  | 00000000:AF:00.0 Off |                    0 |
| N/A   38C    P0    32W / 250W |    255MiB / 16384MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A   2454099      C   blender                           253MiB |
+-----------------------------------------------------------------------------+
</pre>

**Comment by archlitchi** [comment]
well, i guess that's not an issue, maybe 253Mb device memory is enough for that task to process:)

**Comment by umberto10** [comment]
The problem is that, blender itself sees the GPU and, as we can see, it starts gpu process, but even if I select the calculations with GPU usage, it just make it on the CPU instead.
And I don't know which part of this communication is responsible for that.
Maybe I'll describe my case, I want to create accelerated pod with bender na turboVNC server in order to connect to it from my home and visualize some models. Should it be possible with yours plugin? because you wrote that video is not supported, so I don't know if my case is even possible.
