### ISSUE TITLE
Pytorch reports error message "Event device type CUDA does not match blocking stream's device type CPU."

### ISSUE THREAD

**Issue by latituder** [Project-HAMi/HAMi#202]
Nvidia Driver Version: 530.30.02
CUDA Version: 12.1
HAMI with Pytorch 2.2.1 and CUDA 12.1 (Or CUDA 12.2), the job get error message says:
"Event device type CUDA does not match blocking stream's device type CPU."

what additional info do you need to troubleshoot the issue?

**Comment by iyeshuru** [comment]
+1

**Comment by ShihanYang** [comment]
has this problem been solved?
