### ISSUE TITLE
add robot for issue or pr

### ISSUE THREAD

**Issue by calvin0327** [Project-HAMi/HAMi#204]
We need a robot to automatically help us perform github actions to reduce manual operations. Operations like these:
/kind feature, /cc reviewer, /retest, /retitle, etc.

After my research, there are two ways:

1. Lightweight action: https://github.com/wzshiming/gh-ci-bot
  benefits: which offers simplicity and requires no deployment of additional services
  disadvantages: it incurs a delay of approximately 2 seconds due to the execution of the CI workflow
  here's an example: https://github.com/cloudtty/cloudtty/pull/383

2. Using k8s robot: https://docs.prow.k8s.io/docs/getting-started-deploy/
   benefits: which provides numerous functionalities and ensures swift response times
   disadvantages: the prow service needs to be deployed in the public cloud environment and establishing connectivity with the repository through webhooks.
  
  
@archlitchi which option do you think is more suitable for us?

**Comment by archlitchi** [comment]
I think lightweight is fine for us now
