### ISSUE TITLE
我在openshift4平台上使用该项目，vgpu-scheduler pod里面的2个容器有报错分别如下：

### ISSUE THREAD

**Issue by fu7100** [Project-HAMi/HAMi#21]
#oc logs --tail 100 -f vgpu-scheduler-578667c5b8-njg9z -ckube-scheduler   -n kube-system
E0516 09:14:47.783995       1 reflector.go:123] k8s.io/client-go/informers/factory.go:134: Failed to list *v1beta1.CSINode: the server could not find the requested resource
I0516 09:14:48.784245       1 reflector.go:158] Listing and watching *v1beta1.CSINode from k8s.io/client-go/informers/factory.go:134
E0516 09:14:48.786670       1 reflector.go:123] k8s.io/client-go/informers/factory.go:134: Failed to list *v1beta1.CSINode: the server could not find the requested resource
I0516 09:14:49.786922       1 reflector.go:158] Listing and watching *v1beta1.CSINode from k8s.io/client-go/informers/factory.go:134
E0516 09:14:49.794717       1 reflector.go:123] k8s.io/client-go/informers/factory.go:134: Failed to list *v1beta1.CSINode: the server could not find the requested resource

# oc logs --tail 100 -f vgpu-scheduler-578667c5b8-njg9z vgpu-scheduler-extender   -n kube-system
2022/05/16 09:06:31 http: TLS handshake error from 10.128.0.1:35200: remote error: tls: bad certificate
2022/05/16 09:06:31 http: TLS handshake error from 10.128.0.1:35210: remote error: tls: bad certificate
2022/05/16 09:06:32 http: TLS handshake error from 10.128.0.1:35220: remote error: tls: bad certificate
2022/05/16 09:06:32 http: TLS handshake error from 10.128.0.1:35222: remote error: tls: bad certificate
I0516 09:06:44.585620       1 reflector.go:530] pkg/mod/k8s.io/client-go@v0.21.2/tools/cache/reflector.go:167: Watch close - *v1.Pod total 30 items received
2022/05/16 09:07:45 http: TLS handshake error from 10.128.0.1:36328: remote error: tls: bad certificate
2022/05/16 09:07:45 http: TLS handshake error from 10.128.0.1:36330: remote error: tls: bad certificate
2022/05/16 09:07:45 http: TLS handshake error from 10.128.0.1:36332: remote error: tls: bad certificate
2022/05/16 09:07:45 http: TLS handshake error from 10.128.0.1:36334: remote error: tls: bad certificate
2022/05/16 09:07:45 http: TLS handshake error from 10.128.0.1:36336: remote error: tls: bad certificate

**Comment by archlitchi** [comment]
k8s版本是多少呢
