### ISSUE TITLE
Support hunger priority scheduling

### ISSUE THREAD

**Issue by zeroguar** [Project-HAMi/HAMi#245]
### 1. Issue or feature description
supports prioritizing the complete allocation of resources for individual GPUs in a node, allowing for the presence of idle GPUs
### 3. Information to [attach](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/) (optional if deemed irrelevant)

Common error checking:
- [ ] The output of `nvidia-smi -a` on your host
- [ ] Your docker or containerd configuration file (e.g: `/etc/docker/daemon.json`)
- [ ] The vgpu-device-plugin container logs
- [ ] The vgpu-scheduler container logs
- [ ] The kubelet logs on the node (e.g: `sudo journalctl -r -u kubelet`)

Additional information that might help better understand your environment and reproduce the bug:
- [ ] Docker version from `docker version`
- [ ] Docker command, image and tag used
- [ ] Kernel version from `uname -a`
- [ ] Any relevant kernel output lines from `dmesg`

**Comment by lengrongfu** [comment]
@zeroguar Please check if this PR meets your requirements?
https://github.com/Project-HAMi/HAMi/pull/152
