### ISSUE TITLE
cuInit failed:999

### ISSUE THREAD

**Issue by TymonLee** [Project-HAMi/HAMi#264]
### 1. Issue or feature description

I am using older version of k8s-vgpu-scheduler project (v2.3.6 I guess). Recently some users were encountered "cuInit failed:999" in their logs as shown in the picture below. But `nvidia-smi` shows no abnormalities. Any ideas?

![img_v3_029r_43eec1ce-26e4-4f6c-95ee-a8851c52280g](https://github.com/Project-HAMi/HAMi/assets/23135265/57ae2f7c-38b6-47d9-a07a-b32e74da84ad)

### 3. Information to [attach](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/) (optional if deemed irrelevant)

Common error checking:
- [ ] The output of `nvidia-smi -a` on your host

> root@mapping-pipeline-1118748-1712814689-single-pipeline-17244559:~/workspace# nvidia-smi
> [4pdvGPU Msg(930:139816407443264:libvgpu.c:870)]: Initializing.....
> [4pdvGPU Warn(930:139816407443264:utils.c:282)]: get default cuda 1 from (null)
> Thu Apr 11 14:03:46 2024       
> +---------------------------------------------------------------------------------------+
> | NVIDIA-SMI 535.129.03             Driver Version: 535.129.03   CUDA Version: 12.2     |
> |-----------------------------------------+----------------------+----------------------+
> | GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
> | Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
> |                                         |                      |               MIG M. |
> |=========================================+======================+======================|
> |   0  NVIDIA GeForce RTX 3090        Off | 00000000:48:00.0 Off |                  N/A |
> | 51%   27C    P8              28W / 350W |      0MiB /  1288MiB |      0%      Default |
> |                                         |                      |                  N/A |
> +-----------------------------------------+----------------------+----------------------+
>                                                                                          
> +---------------------------------------------------------------------------------------+
> | Processes:                                                                            |
> |  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
> |        ID   ID                                                             Usage      |
> |=======================================================================================|
> |  No running processes found                                                           |
> +---------------------------------------------------------------------------------------+
> [4pdvGPU Msg(930:139816407443264:multiprocess_memory_limit.c:477)]: Calling exit handler 930

- [ ] Your docker or containerd configuration file (e.g: `/etc/docker/daemon.json`)

> root@10-16-10-29:/# cat /etc/containerd/config.toml
> version = 2
> root = "/var/lib/docker/"
> state = "/run/containerd"
> oom_score = 0
> 
> [grpc]
>   max_recv_message_size = 16777216
>   max_send_message_size = 16777216
> 
> [debug]
>   level = "info"
> 
> [metrics]
>   address = ""
>   grpc_histogram = false
> 
> [plugins]
>   [plugins."io.containerd.grpc.v1.cri"]
>     sandbox_image = "k8s.gcr.io/pause:3.6"
>     max_container_log_line_size = -1
>     [plugins."io.containerd.grpc.v1.cri".containerd]
>       default_runtime_name = "nvidia"
>       snapshotter = "overlayfs"
>       [plugins."io.containerd.grpc.v1.cri".containerd.runtimes]
>         [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.nvidia]
>           privileged_without_host_devices = false
>           runtime_engine = ""
>           runtime_root = ""
>           runtime_type = "io.containerd.runc.v2"
>           [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.nvidia.options]
>             BinaryName = "/usr/bin/nvidia-container-runtime"
>             systemdCgroup = true
>     [plugins."io.containerd.grpc.v1.cri".registry]
>       [plugins."io.containerd.grpc.v1.cri".registry.mirrors]
>         [plugins."io.containerd.grpc.v1.cri".registry.mirrors."master0:5000"]
>           endpoint = ["http://10.16.10.163:5000"]
>           [plugins."io.containerd.grpc.v1.cri".registry.configs."master0:5000".tls]
>             insecure_skip_verify = true
>         [plugins."io.containerd.grpc.v1.cri".registry.mirrors."docker.io"]
>           endpoint = ["https://registry-1.docker.io"]
>         [plugins."io.containerd.grpc.v1.cri".registry.mirrors."deeproute-simulation-registry-registry-vpc.cn-shenzhen.cr.aliyuncs.com"]
>           endpoint = ["https://reg.deeproute.ai:443"]
> 
> 
> - [ ] The vgpu-device-plugin container logs
> - 

- [ ] The vgpu-scheduler container logs
- [ ] The kubelet logs on the node (e.g: `sudo journalctl -r -u kubelet`)

Additional information that might help better understand your environment and reproduce the bug:
- [ ] Docker version from `docker version`
- [ ] Docker command, image and tag used
- [ ] Kernel version from `uname -a`

Ubuntu 20.04.6 LTS

- [ ] Any relevant kernel output lines from `dmesg`

**Comment by archlitchi** [comment]
Older version may not be compatible with latest cuda, upgrade to HAMi:v2.3.9 is recommended

**Comment by TymonLee** [comment]
> Older version may not be compatible with latest cuda, upgrade to HAMi:v2.3.9 is recommended

Actually, we have upgraded to HAMi:v2.3.9 but faced the same error, so we rollback to older version. 

Now it's hard to find out the reason. No more logs are available to help find the root cause.

**Comment by TymonLee** [comment]
Update: I changed the cgroup from systemd to cgroupfs and it also worked for this issue.
