### ISSUE TITLE
vgpu调度器安装

### ISSUE THREAD

**Issue by chenxj1997** [Project-HAMi/HAMi#28]
内部网络不能访问githu.io 离线如何安装

**Comment by archlitchi** [comment]
离线安装的话，可以clone repo，然后在{repo path}/charts/ 目录下执行helm install vgpu vgpu --set xxxx -n kube-system，

但是需要修改charts/vgpu/values.yaml里面的（各！个！）image字段指向本地的镜像，当然，这些镜像需要从外网下载下来上传本地
