### ISSUE TITLE
国产显卡支持问题

### ISSUE THREAD

**Issue by zhangQiWorr** [Project-HAMi/HAMi#292]
支持列表中显示能够支持海光和寒武纪显卡的调度和共享切分，对NVIDIA显卡的算力和显存切分通过libvgpu实现的，想请问一下，是否对于国产显卡的显存切分是怎么实现的？ 在使用国产显卡时，应该也需要安装相应厂商的显卡驱动和运行时吧？

**Comment by archlitchi** [comment]
> 支持列表中显示能够支持海光和寒武纪显卡的调度和共享切分，对NVIDIA显卡的算力和显存切分通过libvgpu实现的，想请问一下，是否对于国产显卡的显存切分是怎么实现的？ 在使用国产显卡时，应该也需要安装相应厂商的显卡驱动和运行时吧？

国产卡的支持是我们和厂商合作开发的，厂商提供容器层的硬隔离功能，哈密瓜负责将厂商的功能接入，大部分只需要安装对应的驱动就可以，可以参考安装文档

**Comment by zhangQiWorr** [comment]
> > 支持列表中显示能够支持海光和寒武纪显卡的调度和共享切分，对NVIDIA显卡的算力和显存切分通过libvgpu实现的，想请问一下，是否对于国产显卡的显存切分是怎么实现的？ 在使用国产显卡时，应该也需要安装相应厂商的显卡驱动和运行时吧？
> 
> 国产卡的支持是我们和厂商合作开发的，厂商提供容器层的硬隔离功能，哈密瓜负责将厂商的功能接入，大部分只需要安装对应的驱动就可以，可以参考安装文档

感谢回复
