### ISSUE TITLE
framework support

### ISSUE THREAD

**Issue by lichman0405** [Project-HAMi/HAMi#3]
Hi there!
Glad to you open source the scheduler and it supports most of famous DL framework.
However, what if I try to deploy paddle or paddle serving on a container with vGPU, is it in the same way?

my server os: centos 7.9, kernel 4.19.12-1.el7 X86
docker version 20.10

**Comment by archlitchi** [comment]
Yeah, It works in the same way. If you encountered any problem during the process, feel free to submit an issue here or in slack.
