### ISSUE TITLE
helm install vgpu vgpu-charts/vgpu怎么安装？

### ISSUE THREAD

**Issue by yiyangwang** [Project-HAMi/HAMi#317]
helm install vgpu vgpu-charts/vgpu --set devicePlugin.deviceMemoryScaling=5
这个repo vgpu-charts/vgpu 从哪里安装？

**Comment by archlitchi** [comment]
please see the document here: https://github.com/Project-HAMi/HAMi?tab=readme-ov-file#install-and-uninstall
