### ISSUE TITLE
Project-HAMi/ascend-device-plugin 项目没了

### ISSUE THREAD

**Issue by zlianzhuang** [Project-HAMi/HAMi#331]
https://github.com/Project-HAMi/ascend-device-plugin/blob/master/build/ascendplugin-910-hami.yaml

根据ascend文档的内容。安装device-plugin的时候，发现不能下载了。

**Comment by archlitchi** [comment]
不好意思，测试时遇到了问题，暂时下线了，如果你也想参与测试的话，可以加我微信 “xuanzong4493"

**Comment by Yzz-Ymin** [comment]
请问910后续还会支持吗
