### ISSUE TITLE
当前支持多卡调度，但并不支持不同卡分配不同的资源

### ISSUE THREAD

**Issue by HandsomeWu1** [Project-HAMi/HAMi#333]
当前的系统能够支持多块cpu，但是目前也仅支持平均分配资源，无法实现按需分配
例如：卡1目前剩余显存1000m，卡2剩余8000m，那么这时候申请两块vgpu，显存需求为7000，会一直处于pending状态，但是完全可以是卡1给1000，卡2给6000

**Comment by archlitchi** [comment]
目前的分配方式既不是按需分配，也不是平均分配，申请2张卡，显存7000的结果是“2张卡都分配7000”
