### ISSUE TITLE
Can I use vgpu-scheduler-extender only？

### ISSUE THREAD

**Issue by hzliangbin** [Project-HAMi/HAMi#359]
### 1. Issue or feature description
Hi, I am still using Kubernetes version 1.11 in the production environment. 

After research, I found that the HAMi project's GPU scheduling and compute/memory isolation modules meet our needs. I would like to inquire if it is possible to tailor the HAMi project to exclude the hami-scheduler for global unified scheduling, and instead only handle the GPU scheduling part( combined the vgpu-scheduler-extender with our kube-scheduler 1.11). If feasible, I hope to get your response and some suggestions for furthe custom development.

Waiting for your reply.

**Comment by hzliangbin** [comment]
@lengrongfu @archlitchi

**Comment by wawa0210** [comment]
Can you describe your needs in detail?

Currently, HAMi extends the second kube-scheduler through the scheduler-extender method. If you do not need an additional scheduler, you can also add a sidecar extension to the existing kube-scheduler.

**Comment by hzliangbin** [comment]
> Can you describe your needs in detail?
> 
> Currently, HAMi extends the second kube-scheduler through the scheduler-extender method. If you do not need an additional scheduler, you can also add a sidecar extension to the existing kube-scheduler.

get it
