### ISSUE TITLE
HAMi需要Node Feature Discovery或者GPU Feature Discovery吗？

### ISSUE THREAD

**Issue by janetat** [Project-HAMi/HAMi#365]
# 背景
1. 集群中有gpu-operator，安装了Node Feature Discovery和GPU Feature Discovery。
2. HAMi的调度需要依赖这两个组件吗？如果同时存在，是否有冲突？

**Comment by haitwang-cloud** [comment]
@janetat 不需要。我现在就是这么用的。这些组件的功能不冲突，因为它们的定位不同。Node Feature Discovery和GPU Feature Discovery旨在发现与节点相关的信息，并在创建新标签时显示这些信息。而Hami不依赖这些组件来实现其功能。
