### ISSUE TITLE
学习过程发现内核部分，引用库

### ISSUE THREAD

**Issue by sharfy** [Project-HAMi/HAMi#37]
您好，在学习过程发现libvgpu.so和另外一个引用库没有源代码，请问是否未开源，有开源计划吗，谢谢？

**Comment by archlitchi** [comment]
这一部分有合规性风险，目前没有开源的规划，不过目前有个实现类似功能的开源项目，你可以参考一下https://github.com/tkestack/vcuda-controller

**Comment by sharfy** [comment]
这个项目不太适合，想研究一下显存虚拟化这块技术
