### ISSUE TITLE
How to solve failed calling webhook?

### ISSUE THREAD

**Issue by GuHeeM** [Project-HAMi/HAMi#379]
After installing HAMi, I deployed a gpu pod, got:
Failed calling webhook, failing open vgpu.hami.io: failed calling webhook "vgpu.hami.io": failed to call webhook: Post "[https://hami-scheduler.kube-system.svc:443/webhook?timeout=30s](https://hami-scheduler.kube-system.svc/webhook?timeout=30s)": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
E0707 11:53:33.346585 1 dispatcher.go:180] failed calling webhook "vgpu.hami.io": failed to call webhook: Post "[https://hami-scheduler.kube-system.svc:443/webhook?timeout=30s](https://hami-scheduler.kube-system.svc/webhook?timeout=30s)": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers).

Through: kubectl get po -n kube-system, the hami-device-plugin pods are running.

Capacity:
 cpu:                24
 ephemeral-storage:  597903888Ki
 hugepages-1Gi:      0
 hugepages-2Mi:      0
 memory:             32545252Ki
 nvidia.com/gpu:     0
 pods:               110
Allocatable:
 cpu:                24
 ephemeral-storage:  551028222269
 hugepages-1Gi:      0
 hugepages-2Mi:      0
 memory:             32442852Ki
 nvidia.com/gpu:     0
 pods:               110

Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted.)
  Resource        Requests    Limits
  cpu             850m (3%)   0 (0%)
  memory          240Mi (0%)  340Mi (1%)
  nvidia.com/gpu  0 

but has the following error for the gpu-pod
![image](https://github.com/Project-HAMi/HAMi/assets/32035205/8a838666-7a8d-4b1b-84d0-261829c4a08b)

How to solve this problem?

**Comment by archlitchi** [comment]
I've seen your email, please check if the scheduler is up and running, curl {scheduler node ip}:31993/metrics, and see if you get the overview of the devices in cluster

**Comment by GuHeeM** [comment]
> I've seen your email, please check if the scheduler is up and running, curl {scheduler node ip}:31993/metrics, and see if you get the overview of the devices in cluster

I checked the curl metric and got some overview of my devices, like a device of A800 node:

HELP GPUDeviceCoreAllocated Device core allocated for a certain GPU
TYPE GPUDeviceCoreAllocated gauge
GPUDeviceCoreAllocated{deviceidx="0",deviceuuid="GPU-326c6736-971c-5fe3-2403-6824f6d98555",nodeid="gpu010.cluster.cn",zone="vGPU"} 0
GPUDeviceCoreAllocated{deviceidx="0",deviceuuid="GPU-3508992b-8b73-9470-88dd-7afc92d3ad34",nodeid="gpu010.cluster.cn",zone="vGPU"} 0
GPUDeviceCoreAllocated{deviceidx="0",deviceuuid="GPU-6c9cedb6-571e-6038-386a-48db12d4c30d",nodeid="c10240901-legion-ren9000k-34irz",zone="vGPU"} 0
GPUDeviceCoreAllocated{deviceidx="0",deviceuuid="GPU-7400f29b-294d-d4ae-f98d-cbda0ae1b576",nodeid="gpu010.cluster.cn",zone="vGPU"} 0
GPUDeviceCoreAllocated{deviceidx="0",deviceuuid="GPU-96eab9d1-4a92-0177-f5d4-83ad80f53125",nodeid="node4-legion-ren9000k-34irz",zone="vGPU"} 0
GPUDeviceCoreAllocated{deviceidx="0",deviceuuid="GPU-ab41b334-abce-634f-6fd1-671874338ecd",nodeid="gpu010.cluster.cn",zone="vGPU"} 0
GPUDeviceCoreAllocated{deviceidx="0",deviceuuid="GPU-ccf54094-93ad-ea86-0f52-1a2491954a3d",nodeid="gpu010.cluster.cn",zone="vGPU"} 0
GPUDeviceCoreAllocated{deviceidx="0",deviceuuid="GPU-cd2196e0-c8ad-49b1-aded-aa8ac9486743",nodeid="gpu010.cluster.cn",zone="vGPU"} 0
GPUDeviceCoreAllocated{deviceidx="0",deviceuuid="GPU-eff66f24-3079-61fa-fc06-3087e43e6ab2",nodeid="gpu010.cluster.cn",zone="vGPU"} 0
GPUDeviceCoreAllocated{deviceidx="0",deviceuuid="GPU-fa8952f1-d966-5b6c-b742-869ec5f205ab",nodeid="gpu010.cluster.cn",zone="vGPU"} 0

HELP GPUDeviceCoreLimit Device memory core limit for a certain GPU
TYPE GPUDeviceCoreLimit gauge
GPUDeviceCoreLimit{deviceidx="0",deviceuuid="GPU-326c6736-971c-5fe3-2403-6824f6d98555",nodeid="gpu010.cluster.cn",zone="vGPU"} 100
GPUDeviceCoreLimit{deviceidx="0",deviceuuid="GPU-3508992b-8b73-9470-88dd-7afc92d3ad34",nodeid="gpu010.cluster.cn",zone="vGPU"} 100
GPUDeviceCoreLimit{deviceidx="0",deviceuuid="GPU-6c9cedb6-571e-6038-386a-48db12d4c30d",nodeid="c10240901-legion-ren9000k-34irz",zone="vGPU"} 100
GPUDeviceCoreLimit{deviceidx="0",deviceuuid="GPU-7400f29b-294d-d4ae-f98d-cbda0ae1b576",nodeid="gpu010.cluster.cn",zone="vGPU"} 100
GPUDeviceCoreLimit{deviceidx="0",deviceuuid="GPU-96eab9d1-4a92-0177-f5d4-83ad80f53125",nodeid="node4-legion-ren9000k-34irz",zone="vGPU"} 100
GPUDeviceCoreLimit{deviceidx="0",deviceuuid="GPU-ab41b334-abce-634f-6fd1-671874338ecd",nodeid="gpu010.cluster.cn",zone="vGPU"} 100
GPUDeviceCoreLimit{deviceidx="0",deviceuuid="GPU-ccf54094-93ad-ea86-0f52-1a2491954a3d",nodeid="gpu010.cluster.cn",zone="vGPU"} 100
GPUDeviceCoreLimit{deviceidx="0",deviceuuid="GPU-cd2196e0-c8ad-49b1-aded-aa8ac9486743",nodeid="gpu010.cluster.cn",zone="vGPU"} 100
GPUDeviceCoreLimit{deviceidx="0",deviceuuid="GPU-eff66f24-3079-61fa-fc06-3087e43e6ab2",nodeid="gpu010.cluster.cn",zone="vGPU"} 100
GPUDeviceCoreLimit{deviceidx="0",deviceuuid="GPU-fa8952f1-d966-5b6c-b742-869ec5f205ab",nodeid="gpu010.cluster.cn",zone="vGPU"} 100

HELP GPUDeviceMemoryAllocated Device memory allocated for a certain GPU
TYPE GPUDeviceMemoryAllocated gauge
GPUDeviceMemoryAllocated{devicecores="0",deviceidx="0",deviceuuid="GPU-326c6736-971c-5fe3-2403-6824f6d98555",nodeid="gpu010.cluster.cn",zone="vGPU"} 0
GPUDeviceMemoryAllocated{devicecores="0",deviceidx="0",deviceuuid="GPU-3508992b-8b73-9470-88dd-7afc92d3ad34",nodeid="gpu010.cluster.cn",zone="vGPU"} 0
GPUDeviceMemoryAllocated{devicecores="0",deviceidx="0",deviceuuid="GPU-6c9cedb6-571e-6038-386a-48db12d4c30d",nodeid="c10240901-legion-ren9000k-34irz",zone="vGPU"} 0
GPUDeviceMemoryAllocated{devicecores="0",deviceidx="0",deviceuuid="GPU-7400f29b-294d-d4ae-f98d-cbda0ae1b576",nodeid="gpu010.cluster.cn",zone="vGPU"} 0
GPUDeviceMemoryAllocated{devicecores="0",deviceidx="0",deviceuuid="GPU-96eab9d1-4a92-0177-f5d4-83ad80f53125",nodeid="node4-legion-ren9000k-34irz",zone="vGPU"} 0
GPUDeviceMemoryAllocated{devicecores="0",deviceidx="0",deviceuuid="GPU-ab41b334-abce-634f-6fd1-671874338ecd",nodeid="gpu010.cluster.cn",zone="vGPU"} 0
GPUDeviceMemoryAllocated{devicecores="0",deviceidx="0",deviceuuid="GPU-ccf54094-93ad-ea86-0f52-1a2491954a3d",nodeid="gpu010.cluster.cn",zone="vGPU"} 0
GPUDeviceMemoryAllocated{devicecores="0",deviceidx="0",deviceuuid="GPU-cd2196e0-c8ad-49b1-aded-aa8ac9486743",nodeid="gpu010.cluster.cn",zone="vGPU"} 0
GPUDeviceMemoryAllocated{devicecores="0",deviceidx="0",deviceuuid="GPU-eff66f24-3079-61fa-fc06-3087e43e6ab2",nodeid="gpu010.cluster.cn",zone="vGPU"} 0
GPUDeviceMemoryAllocated{devicecores="0",deviceidx="0",deviceuuid="GPU-fa8952f1-d966-5b6c-b742-869ec5f205ab",nodeid="gpu010.cluster.cn",zone="vGPU"} 0

HELP GPUDeviceMemoryLimit Device memory limit for a certain GPU
TYPE GPUDeviceMemoryLimit gauge
GPUDeviceMemoryLimit{deviceidx="0",deviceuuid="GPU-326c6736-971c-5fe3-2403-6824f6d98555",nodeid="gpu010.cluster.cn",zone="vGPU"} 4.294967296e+11
GPUDeviceMemoryLimit{deviceidx="0",deviceuuid="GPU-3508992b-8b73-9470-88dd-7afc92d3ad34",nodeid="gpu010.cluster.cn",zone="vGPU"} 4.294967296e+11
GPUDeviceMemoryLimit{deviceidx="0",deviceuuid="GPU-6c9cedb6-571e-6038-386a-48db12d4c30d",nodeid="c10240901-legion-ren9000k-34irz",zone="vGPU"} 1.2878610432e+11
GPUDeviceMemoryLimit{deviceidx="0",deviceuuid="GPU-7400f29b-294d-d4ae-f98d-cbda0ae1b576",nodeid="gpu010.cluster.cn",zone="vGPU"} 4.294967296e+11
GPUDeviceMemoryLimit{deviceidx="0",deviceuuid="GPU-96eab9d1-4a92-0177-f5d4-83ad80f53125",nodeid="node4-legion-ren9000k-34irz",zone="vGPU"} 6.439305216e+10
GPUDeviceMemoryLimit{deviceidx="0",deviceuuid="GPU-ab41b334-abce-634f-6fd1-671874338ecd",nodeid="gpu010.cluster.cn",zone="vGPU"} 4.294967296e+11
GPUDeviceMemoryLimit{deviceidx="0",deviceuuid="GPU-ccf54094-93ad-ea86-0f52-1a2491954a3d",nodeid="gpu010.cluster.cn",zone="vGPU"} 4.294967296e+11
GPUDeviceMemoryLimit{deviceidx="0",deviceuuid="GPU-cd2196e0-c8ad-49b1-aded-aa8ac9486743",nodeid="gpu010.cluster.cn",zone="vGPU"} 4.294967296e+11
GPUDeviceMemoryLimit{deviceidx="0",deviceuuid="GPU-eff66f24-3079-61fa-fc06-3087e43e6ab2",nodeid="gpu010.cluster.cn",zone="vGPU"} 4.294967296e+11
GPUDeviceMemoryLimit{deviceidx="0",deviceuuid="GPU-fa8952f1-d966-5b6c-b742-869ec5f205ab",nodeid="gpu010.cluster.cn",zone="vGPU"} 4.294967296e+11

HELP GPUDeviceSharedNum Number of containers sharing this GPU
TYPE GPUDeviceSharedNum gauge
GPUDeviceSharedNum{deviceidx="0",deviceuuid="GPU-326c6736-971c-5fe3-2403-6824f6d98555",nodeid="gpu010.cluster.cn",zone="vGPU"} 0
GPUDeviceSharedNum{deviceidx="0",deviceuuid="GPU-3508992b-8b73-9470-88dd-7afc92d3ad34",nodeid="gpu010.cluster.cn",zone="vGPU"} 0
GPUDeviceSharedNum{deviceidx="0",deviceuuid="GPU-6c9cedb6-571e-6038-386a-48db12d4c30d",nodeid="c10240901-legion-ren9000k-34irz",zone="vGPU"} 0
GPUDeviceSharedNum{deviceidx="0",deviceuuid="GPU-7400f29b-294d-d4ae-f98d-cbda0ae1b576",nodeid="gpu010.cluster.cn",zone="vGPU"} 0
GPUDeviceSharedNum{deviceidx="0",deviceuuid="GPU-96eab9d1-4a92-0177-f5d4-83ad80f53125",nodeid="node4-legion-ren9000k-34irz",zone="vGPU"} 0
GPUDeviceSharedNum{deviceidx="0",deviceuuid="GPU-ab41b334-abce-634f-6fd1-671874338ecd",nodeid="gpu010.cluster.cn",zone="vGPU"} 0
GPUDeviceSharedNum{deviceidx="0",deviceuuid="GPU-ccf54094-93ad-ea86-0f52-1a2491954a3d",nodeid="gpu010.cluster.cn",zone="vGPU"} 0
GPUDeviceSharedNum{deviceidx="0",deviceuuid="GPU-cd2196e0-c8ad-49b1-aded-aa8ac9486743",nodeid="gpu010.cluster.cn",zone="vGPU"} 0
GPUDeviceSharedNum{deviceidx="0",deviceuuid="GPU-eff66f24-3079-61fa-fc06-3087e43e6ab2",nodeid="gpu010.cluster.cn",zone="vGPU"} 0
GPUDeviceSharedNum{deviceidx="0",deviceuuid="GPU-fa8952f1-d966-5b6c-b742-869ec5f205ab",nodeid="gpu010.cluster.cn",zone="vGPU"} 0

HELP nodeGPUMemoryPercentage GPU Memory Allocated Percentage on a certain GPU
TYPE nodeGPUMemoryPercentage gauge
nodeGPUMemoryPercentage{deviceidx="0",deviceuuid="GPU-326c6736-971c-5fe3-2403-6824f6d98555",nodeid="gpu010.cluster.cn",zone="vGPU"} 0
nodeGPUMemoryPercentage{deviceidx="0",deviceuuid="GPU-3508992b-8b73-9470-88dd-7afc92d3ad34",nodeid="gpu010.cluster.cn",zone="vGPU"} 0
nodeGPUMemoryPercentage{deviceidx="0",deviceuuid="GPU-6c9cedb6-571e-6038-386a-48db12d4c30d",nodeid="c10240901-legion-ren9000k-34irz",zone="vGPU"} 0
nodeGPUMemoryPercentage{deviceidx="0",deviceuuid="GPU-7400f29b-294d-d4ae-f98d-cbda0ae1b576",nodeid="gpu010.cluster.cn",zone="vGPU"} 0
nodeGPUMemoryPercentage{deviceidx="0",deviceuuid="GPU-96eab9d1-4a92-0177-f5d4-83ad80f53125",nodeid="node4-legion-ren9000k-34irz",zone="vGPU"} 0
nodeGPUMemoryPercentage{deviceidx="0",deviceuuid="GPU-ab41b334-abce-634f-6fd1-671874338ecd",nodeid="gpu010.cluster.cn",zone="vGPU"} 0
nodeGPUMemoryPercentage{deviceidx="0",deviceuuid="GPU-ccf54094-93ad-ea86-0f52-1a2491954a3d",nodeid="gpu010.cluster.cn",zone="vGPU"} 0
nodeGPUMemoryPercentage{deviceidx="0",deviceuuid="GPU-cd2196e0-c8ad-49b1-aded-aa8ac9486743",nodeid="gpu010.cluster.cn",zone="vGPU"} 0
nodeGPUMemoryPercentage{deviceidx="0",deviceuuid="GPU-eff66f24-3079-61fa-fc06-3087e43e6ab2",nodeid="gpu010.cluster.cn",zone="vGPU"} 0
nodeGPUMemoryPercentage{deviceidx="0",deviceuuid="GPU-fa8952f1-d966-5b6c-b742-869ec5f205ab",nodeid="gpu010.cluster.cn",zone="vGPU"} 0
 HELP nodeGPUOverview GPU overview on a certain node
TYPE nodeGPUOverview gauge
nodeGPUOverview{devicecores="0",deviceidx="0",devicememorylimit="122820",devicetype="NVIDIA-NVIDIA GeForce RTX 4090",deviceuuid="GPU-6c9cedb6-571e-6038-386a-48db12d4c30d",nodeid="c10240901-legion-ren9000k-34irz",sharedcontainers="0",zone="vGPU"} 0
nodeGPUOverview{devicecores="0",deviceidx="0",devicememorylimit="409600",devicetype="NVIDIA-NVIDIA A800-SXM4-80GB",deviceuuid="GPU-326c6736-971c-5fe3-2403-6824f6d98555",nodeid="gpu010.cluster.cn",sharedcontainers="0",zone="vGPU"} 0
nodeGPUOverview{devicecores="0",deviceidx="0",devicememorylimit="409600",devicetype="NVIDIA-NVIDIA A800-SXM4-80GB",deviceuuid="GPU-3508992b-8b73-9470-88dd-7afc92d3ad34",nodeid="gpu010.cluster.cn",sharedcontainers="0",zone="vGPU"} 0
nodeGPUOverview{devicecores="0",deviceidx="0",devicememorylimit="409600",devicetype="NVIDIA-NVIDIA A800-SXM4-80GB",deviceuuid="GPU-7400f29b-294d-d4ae-f98d-cbda0ae1b576",nodeid="gpu010.cluster.cn",sharedcontainers="0",zone="vGPU"} 0
nodeGPUOverview{devicecores="0",deviceidx="0",devicememorylimit="409600",devicetype="NVIDIA-NVIDIA A800-SXM4-80GB",deviceuuid="GPU-ab41b334-abce-634f-6fd1-671874338ecd",nodeid="gpu010.cluster.cn",sharedcontainers="0",zone="vGPU"} 0
nodeGPUOverview{devicecores="0",deviceidx="0",devicememorylimit="409600",devicetype="NVIDIA-NVIDIA A800-SXM4-80GB",deviceuuid="GPU-ccf54094-93ad-ea86-0f52-1a2491954a3d",nodeid="gpu010.cluster.cn",sharedcontainers="0",zone="vGPU"} 0
nodeGPUOverview{devicecores="0",deviceidx="0",devicememorylimit="409600",devicetype="NVIDIA-NVIDIA A800-SXM4-80GB",deviceuuid="GPU-cd2196e0-c8ad-49b1-aded-aa8ac9486743",nodeid="gpu010.cluster.cn",sharedcontainers="0",zone="vGPU"} 0
nodeGPUOverview{devicecores="0",deviceidx="0",devicememorylimit="409600",devicetype="NVIDIA-NVIDIA A800-SXM4-80GB",deviceuuid="GPU-eff66f24-3079-61fa-fc06-3087e43e6ab2",nodeid="gpu010.cluster.cn",sharedcontainers="0",zone="vGPU"} 0
nodeGPUOverview{devicecores="0",deviceidx="0",devicememorylimit="409600",devicetype="NVIDIA-NVIDIA A800-SXM4-80GB",deviceuuid="GPU-fa8952f1-d966-5b6c-b742-869ec5f205ab",nodeid="gpu010.cluster.cn",sharedcontainers="0",zone="vGPU"} 0
nodeGPUOverview{devicecores="0",deviceidx="0",devicememorylimit="61410",devicetype="NVIDIA-NVIDIA GeForce RTX 4070 Ti",deviceuuid="GPU-96eab9d1-4a92-0177-f5d4-83ad80f53125",nodeid="node4-legion-ren9000k-34irz",sharedcontainers="0",zone="vGPU"} 0

**Comment by GuHeeM** [comment]
solved by adding schedulerName:hami-scheduler, thanks to the support team.
