### ISSUE TITLE
containerd 怎么使用nvidia-docker2

### ISSUE THREAD

**Issue by chenxj1997** [Project-HAMi/HAMi#38]
当前环境为containerd 没有docker
使用的是nvidia-container-toolkit
没有安装nvidia-docker2
使用vgpu时
无gpu镜像会报找不到libcuda.so.1文件
containerd环境需要进行什么配置？

**Comment by niconical** [comment]
可以参考这个
https://github.com/NVIDIA/k8s-device-plugin#configure-containerd
