### ISSUE TITLE
请教一下，hami接入到prometheus中后，Device_utilization_desc_of_container这个指标一直为0，会是什么原因呢？

### ISSUE THREAD

**Issue by Ryan817** [Project-HAMi/HAMi#403]
## 问题描述
我把hami的metrics通过servicemonitor暴露给Prometheus集群，然后测了一下监控指标。其他几个指标都可以正常看到数据，唯独 Device_utilization_desc_of_container 这个指标一直都是0，请问这种情况是什么原因造成的呢？

备注：
- 整张卡的利用率指标 DCGM_FI_DEV_GPU_UTIL 是有数据的

**Comment by chaunceyjiang** [comment]
What is the value set for `nvidia.com/gpucores` in your pod?

**Comment by chaunceyjiang** [comment]
> nvidia.com/gpucores 配置成100之后

Currently, when `nvidia.com/gpucores` is set to 100, `Device_utilization_desc_of_container` will always be 0. This is a known issue, and I'm trying to fix it.
