### ISSUE TITLE
Metrics只能统计到一部分信息，丢失Device_memory_desc_of_container等信息

### ISSUE THREAD

**Issue by ymbZzz** [Project-HAMi/HAMi#426]
# 描述
调用http://{IP}:{monitorPort}/metrics。
只能拿到HostCoreUtilization、HostGPUMemoryUsage
期望获取Device_memory_desc_of_container、Device_utilization_desc_of_container等信息
# 截图
## POD信息：
![image](https://github.com/user-attachments/assets/f12c1f0a-8793-490a-8fc3-14a8b1d79886)
![image](https://github.com/user-attachments/assets/0a43c05a-cfae-4661-b7bf-4681856169f2)
![image](https://github.com/user-attachments/assets/80a59a99-ceff-43c6-a184-5e71b5e31da2)
## device plugin
![image](https://github.com/user-attachments/assets/d02771a4-a43a-49ad-937b-3ede57324f21)
# 问题
为什么获取不到Device_memory_desc_of_container等信息

**Comment by shoted** [comment]
我也遇到同样的问题，不知道为啥

**Comment by bxhzzx** [comment]
@ymbZzz 同样遇到只有`HostGPUMemoryUsage`和`HostCoreUtilization`指标的情况， 请问你是否解决了， 如何解决的？谢谢
