### ISSUE TITLE
GPUSchedulerPolicy是spread，scheduler的31993端口查到的pod调度到的物理GPU卡和device plugin的31992端口查询到的pod落位物理卡不是一张卡，底层统一调度到了0号卡

### ISSUE THREAD

**Issue by panorama47** [Project-HAMi/HAMi#442]
问题描述：
2.3.13版本，node是binpakc策略，gpu卡是spread策略，scheduler调度符合要求，四个container均匀分配到底层一台机器的四张卡上，但是device plugin查看，发现四个containerd实际落位在同一张卡——机器的GPU id=0的卡上，nvidia-smi命令也发现此现象。

图片：
![_cgi-bin_mmwebwx-bin_webwxgetmsgimg__ MsgID=4005009560423660400 skey=@crypt_4f634d77_f235ae5b21ec67074eb635a5cdfcfa90 mmweb_appid=wx_webfilehelper](https://github.com/user-attachments/assets/73334a1d-9ebc-46a5-a4c1-eba89a6e88fc)

![_cgi-bin_mmwebwx-bin_webwxgetmsgimg__ MsgID=3467449568927937729 skey=@crypt_4f634d77_f235ae5b21ec67074eb635a5cdfcfa90 mmweb_appid=wx_webfilehelper](https://github.com/user-attachments/assets/c2354241-50d4-48a9-a817-b28a9282791e)
![_cgi-bin_mmwebwx-bin_webwxgetmsgimg__ MsgID=5732062825371688496 skey=@crypt_4f634d77_f235ae5b21ec67074eb635a5cdfcfa90 mmweb_appid=wx_webfilehelper](https://github.com/user-attachments/assets/5a17c450-b2ef-4081-bb71-d078dcc2da42)

**Comment by lengrongfu** [comment]
you can use `nvidia-smi -L` command to check gpu uuid.

**Comment by archlitchi** [comment]
after a discussion with the issue owner, we discover that the issue is caused by manually overwrite env["NVIDIA_VISIBLE_DEVICES"], so it overwrites the GPU assigned by scheduler
