### ISSUE TITLE
咱们的vgpu共享技术是类似腾讯的vCUDA还是阿里的cGPU呢？

### ISSUE THREAD

**Issue by rexxar-liang** [Project-HAMi/HAMi#46]
[这里](https://zhuanlan.zhihu.com/p/268901942)是一篇介绍GPU共享技术的分享，里面介绍了两种GPU共享技术的方案：
1、CUDA层劫持(腾讯云的vCUDA（已下线？）)
2、GPU驱动层劫持(阿里云cGPU)
第1种方案的缺点是对CUDA依赖，CUDA新版本增加功能或者接口变更，第1种方案可能就不适用了
总体看第2种方案更优越一些。

腾讯云后来新的GPU共享方案[qGPU](https://cloud.tencent.com/document/product/457/61448)，应该采用的是第2种方案。

咱们的vGPU是哪一种呢？从之前的[issue](https://github.com/4paradigm/k8s-vgpu-scheduler/issues/27)看起来像是第1种。

如果vGPU采用第2种方案的话，是值得赞赏和尝试的。

**Comment by archlitchi** [comment]
第一种，不过我们会积极适配cuda的版本更新，目前完全支持最新版本的cuda（11.7），使用在容器编排工具k8s上已经是非常成熟的技术，经过了许多用户的验证，可以放心使用：）
