### ISSUE TITLE
helm安装过程中报错，chart "hami" not found in hami-charts index.

### ISSUE THREAD

**Issue by beast-R** [Project-HAMi/HAMi#463]
k8s环境所处内网，将https://project-hami.github.io/HAMi/ 外网地址映射为内网地址http://10.10.200.102:8081/helm-proxy-aliyun/

内网添加仓库 helm repo add hami-charts http://10.10.200.102:8081/helm-proxy-aliyun/ 

helm repo update成功

helm install hami hami-charts/hami --set scheduler.kubeScheduler.imageTag=v1.23.10 -n kube-system 报错
INSTALLTION ERROR :chart "hami" not found in hami-charts index. (try helm repo update ) : no chart name found

helm repo search hami 未找到对应hami版本信息

这个错误是内外网转发的报错吗
![_cgi-bin_mmwebwx-bin_webwxgetmsgimg__ MsgID=1601295297242432029 skey=@crypt_97bb9de9_c64ebbef63eade5ab5d44d8abeaf8dc7 mmweb_appid=wx_webfilehelper](https://github.com/user-attachments/assets/74ad0c37-630e-48c1-abd9-14cb2c65be99)
![Uploading _cgi-bin_mmwebwx-bin_webwxgetmsgimg__&MsgID=527304870179165847&skey=@crypt_97bb9de9_c64ebbef63eade5ab5d44d8abeaf8dc7&mmweb_appid=wx_webfilehelper.jpg…]()

**Comment by archlitchi** [comment]
i guess so, if you are in an offline environment, please follow the offline-installation guild, here http://project-hami.io/docs/installation/offline-installation
