### ISSUE TITLE
未配置nvidia.com/gpu，pod内能用全部gpu卡

### ISSUE THREAD

**Issue by chankay** [Project-HAMi/HAMi#464]
1、版本
k8s 1.23.15， 插件安装脚本如下
<img width="1407" alt="image" src="https://github.com/user-attachments/assets/a6f19fa7-4f2e-4834-ac57-fa7727c53626">

2、现象
resource未配置gpu，pod内nvidia-smi能看到全部gpu卡且能使用
<img width="582" alt="image" src="https://github.com/user-attachments/assets/7a1903d1-3b5d-49f1-8c94-971fb39a24af">

<img width="922" alt="image" src="https://github.com/user-attachments/assets/c30d4a76-05df-4a93-ae23-868567d48b7f">

3、问题
未配置nvidia.com/gpu的情况下是不是应该使用不了gpu

**Comment by singeleaf** [comment]
pod 的完整yaml发出来看看呢

**Comment by chankay** [comment]
> pod 的完整yaml发出来看看呢

apiVersion: "kubeflow.org/v1"
kind: PyTorchJob
metadata:
  name: pytorch-simple
  namespace: kubeflow
spec:
  pytorchReplicaSpecs:
    Master:
      replicas: 1
      restartPolicy: OnFailure
      template:
        spec:
          nodeName: "aitesta100"
          containers:
            - name: pytorch
              image: dlp.geovisearth.com/share/minst:v1
              imagePullPolicy: Always
              command:
                - "python3"
                - "/opt/pytorch-mnist/mnist.py"
                - "--epochs=1000"
#              resources:
#                limits:
#                  nvidia.com/gpu: 1
#                  nvidia.com/gpumem: 1024
    Worker:
      replicas: 3
      restartPolicy: OnFailure
      template:
        spec:
          nodeName: "aitesta100"
          containers:
            - name: pytorch
              image: dlp.geovisearth.com/share/minst:v1
              imagePullPolicy: Always
              command:
                - "python3"
                - "/opt/pytorch-mnist/mnist.py"
                - "--epochs=1000"
                  #              resources:
                  #limits:
                  #nvidia.com/gpu: 1
                  #nvidia.com/gpumem: 1024

**Comment by chankay** [comment]
apiVersion: "kubeflow.org/v1"
kind: PyTorchJob
metadata:
  name: pytorch-simple
  namespace: kubeflow
spec:
  pytorchReplicaSpecs:
    Master:
      replicas: 1
      restartPolicy: OnFailure
      template:
        spec:
          nodeName: "aitesta100"
          containers:
            - name: pytorch
              image: dlp.geovisearth.com/share/minst:v1
              imagePullPolicy: Always
              command:
                - "python3"
                - "/opt/pytorch-mnist/mnist.py"
                - "--epochs=1000"
#              resources:
#                limits:
#                  nvidia.com/gpu: 1
#                  nvidia.com/gpumem: 1024
    Worker:
      replicas: 3
      restartPolicy: OnFailure
      template:
        spec:
          nodeName: "aitesta100"
          containers:
            - name: pytorch
              image: dlp.geovisearth.com/share/minst:v1
              imagePullPolicy: Always
              command:
                - "python3"
                - "/opt/pytorch-mnist/mnist.py"
                - "--epochs=1000"
                  #              resources:
                  #limits:
                  #nvidia.com/gpu: 1
                  #nvidia.com/gpumem: 1024
resource部分是注释掉特意测试的

**Comment by chankay** [comment]
> pod 的完整yaml发出来看看呢

我用了个最简单的pod试了下也是一样的

apiVersion: v1
kind: Pod
metadata:
  name: gpu-test
spec:
  containers:
    - name: jupytertest1
      image: ccr.ccs.tencentyun.com/cube-studio/ubuntu-gpu:cuda11.8.0-cudnn8-python3.9
      command: ["bash", "-c", "sleep 86400"]

**Comment by archlitchi** [comment]
the reason of this issue is the image contains 'NVIDIA_VISIBLE_DEVICES=all' env, so it bypass k8s scheduling and directly interact with nvidia-docker2. you should remove that env from image

**Comment by chankay** [comment]
> the reason of this issue is the image contains 'NVIDIA_VISIBLE_DEVICES=all' env, so it bypass k8s scheduling and directly interact with nvidia-docker2. you should remove that env from image

This solved!  Thank You !
