### ISSUE TITLE
为什么node的Capacity和Allocatable中只有nvidia.com/gpu，没有nvidia.com/gpumem

### ISSUE THREAD

**Issue by liujin1993** [Project-HAMi/HAMi#579]
请问下为什么node的Capacity和Allocatable中只有nvidia.com/gpu，没有nvidia.com/gpumem？有时创建pod之前想先知道总共有多少mem，还剩多少mem。
![image](https://github.com/user-attachments/assets/0895815f-3e2f-4572-903d-f9fb8aed5512)

![image](https://github.com/user-attachments/assets/2dd77108-672c-40de-9889-d95fc2250306)

**Comment by archlitchi** [comment]
集群余量可以通过curl {scheduler node ip}:31993/metrics 查询，没有gpumem是因为现在它是作为nvidia.com/gpu的参数存在，而不是一个独立的可调度资源，所以配置成ignore了

**Comment by liujin1993** [comment]
@archlitchi 感谢! 找到了，GPUDeviceMemoryLimit和GPUDeviceMemoryAllocated分别是卡级别的总量和分配量。需要一个servicemonitor采集scheduler指标才行，用helm部署不会自动创建
