### ISSUE TITLE
[HAMI-core ERROR (pid:7 thread=140360328144640 allocator.c:115)]: cuMemoryAllocate failed res=2

### ISSUE THREAD

**Issue by mazhaoshuo** [Project-HAMi/HAMi#585]
帮忙看下有个下面的错误输出，导致现在推理卡死
插件版本：v2.3.13
没有开启虚拟内存
[HAMI-core ERROR (pid:7 thread=140360328144640 allocator.c:115)]: cuMemoryAllocate failed res=2

**Comment by wawa0210** [comment]
Could you please provide your detailed context according to the template? So that we can better dig.

ps,you can try updating to HAMi v2.4.0, which fixes many issues.

**Comment by wawa0210** [comment]
Due to OOM
