### ISSUE TITLE
监控的数据，有没有画好的grafana dashboard？

### ISSUE THREAD

**Issue by AlawnWong** [Project-HAMi/HAMi#60]
监控的数据，有没有画好的grafana dashboard？

**Comment by archlitchi** [comment]
暂时没有...

**Comment by fangfenghuang** [comment]
我画了一个，可以参考一下，如果还有更好的可以一起分享
[gpu-dashboard.txt](https://github.com/4paradigm/k8s-vgpu-scheduler/files/12459589/gpu-dashboard.txt)
<img width="958" alt="20230829101005" src="https://github.com/4paradigm/k8s-vgpu-scheduler/assets/49675127/67abe73a-cb89-449b-b21f-c421d5570c35">
<img width="431" alt="20230829101055" src="https://github.com/4paradigm/k8s-vgpu-scheduler/assets/49675127/7f1e200c-7b1e-4799-a225-ea1fde3376f9">
