### ISSUE TITLE
gpu pod FailedScheduling

### ISSUE THREAD

**Issue by 3260926861** [Project-HAMi/HAMi#629]
I hope you can give me some suggestions. Thank you

**What happened**:
_**gpu pod FailedScheduling**_

**What you expected to happen**:
the status of gpu pod is running
**How to reproduce it (as minimally and precisely as possible)**:
install the hami according to the install steps, then run the following deployment:
creat gpu-pod01.yaml
<img width="277" alt="50f2231c33e39644163bd157c93da76" src="https://github.com/user-attachments/assets/17cc005c-8f13-40a6-9bb2-3076d67b2a6d">
kubectl apply -f gpu-pod01.yaml
<img width="256" alt="c696655ce63f4183b6565281aa5363c" src="https://github.com/user-attachments/assets/b5371db3-390b-4d45-97e7-973773d4c56e">
kubectl describe pod gpu-pod01
<img width="959" alt="a174fd521aa234c685a60eb023ba483" src="https://github.com/user-attachments/assets/6706d21f-8b2a-4c70-90d4-de12910ec857">
if I don't request gpu mem:
creat gpu-pod02.yaml
<img width="290" alt="d013f2f99cd3fc93f6903eb94749977" src="https://github.com/user-attachments/assets/4f48281c-3666-411d-817b-1188bbbd60a3">
kubectl describe pod gpu-pod01
<img width="947" alt="a365a2a295cb95c271a7e75916b552d" src="https://github.com/user-attachments/assets/358a98bf-b26e-4cfa-bc2e-b1cf96a4b92b">

**Anything else we need to know?**:

- The output of `nvidia-smi -a` on your host
- Your docker or containerd configuration file (e.g: `/etc/docker/daemon.json`)
 Master
 /etc/docker/daemon.json
<img width="631" alt="a37b0efb185ab9e075c2f3c46101890" src="https://github.com/user-attachments/assets/0b0955b4-d89e-4e3b-99d2-4d9fd3757907">
 node1
 /etc/docker/daemon.json
<img width="266" alt="fac5484757c1488808a19bc2560d704" src="https://github.com/user-attachments/assets/6b4104a5-73a0-4af5-b676-158bc760fffd">

- The hami-device-plugin container logs
- The hami-scheduler container logs
- The kubelet logs on the node (e.g: `sudo journalctl -r -u kubelet`)
- Any relevant kernel output lines from `dmesg`

**Environment**:
- HAMi version:
2.4.1
- nvidia driver or other AI device driver version:
- Docker version from `docker version`
- Docker command, image and tag used
- Kernel version from `uname -a`
- Others:
 **kubectl logs kube-apiserver-k8s-master -n kube-system**
<img width="938" alt="8b01cb74f39d627b5a55e7ce6537d28" src="https://github.com/user-attachments/assets/4e30afd1-daa9-43bd-8f50-6209a1c644c3">
<img width="270" alt="297b3cbf9cde6f08f67b2402c3182b7" src="https://github.com/user-attachments/assets/7fde25d7-9cc3-40fe-a754-2c1ec7c4b269">
<img width="608" alt="b24ae8922d9ca57488d2061acfd4963" src="https://github.com/user-attachments/assets/421ae3ed-0810-40e7-a2c7-33fa95bdb92d">

- curl scheduler node ip：31993/metrics
<img width="767" alt="a7ceae331095e0839060b5ed23bb0fd" src="https://github.com/user-attachments/assets/2a55be78-6b5b-437f-a83e-9450f129fc46">

**Comment by Nimbus318** [comment]
目前调度失败的原因是因为 API-Server 调用 webhook 出了问题，所以 Pod 的调度走了 default-scheduler，没有走 hami-scheduler，会导致调度失败，这个 webhook 的服务提供方也是 hami-scheduler 这个 Pod，这个 Pod 看起来是 Running 的，应该没有问题，所以目前排查思路就是网络相关的问题，就是需要搞清楚为什么 APIServer 没有调通 webhook
