### ISSUE TITLE
 If this is not a GPU node, you should set up a toleration or nodeSelector to only deploy this plugin on GPU nodes

### ISSUE THREAD

**Issue by mazhaoshuo** [Project-HAMi/HAMi#641]
版本 V2.4.1
已经安装了nvidia docker插件
 If this is not a GPU node, you should set up a toleration or nodeSelector to only deploy this plugin on GPU nodes
error starting plugins: error creating plugin manager: unable to create plugin manager: platform detection failed
root@master1:~# docker run --rm --runtime=nvidia --gpus all docker.m.daocloud.io/nvidia/cuda:11.3.1-base-ubuntu18.04 nvidia-smi
![image](https://github.com/user-attachments/assets/84830f90-df29-4837-8e9d-51d7096dc261)

![image](https://github.com/user-attachments/assets/1f08a236-d2f8-45ac-b6e6-150314ffc4d0)

![image](https://github.com/user-attachments/assets/f169fc4c-8097-459d-953b-455688efd399)
帮忙看下我已经安装了，但是还是提示没有GPU

**Comment by archlitchi** [comment]
looks like you haven't configured nvidia-docker2, see https://github.com/NVIDIA/k8s-device-plugin?tab=readme-ov-file#preparing-your-gpu-nodes for more details

**Comment by mazhaoshuo** [comment]
![image](https://github.com/user-attachments/assets/17df5a1e-bb64-49d0-bd53-bf4cc8bbcffe)
可以了，配置问题，/etc/docker/daemon.json少了个"default-runtime": "nvidia"配置

**Comment by ewrewrew188** [comment]
我也遇到了这个问题，但我是containered，这个引擎怎么配置？

**Comment by ewrewrew188** [comment]
![Image](https://github.com/user-attachments/assets/f9cda3c8-25be-47d9-aebd-5c9666598ced)
