### ISSUE TITLE
使用一段时间之后，不能再进行共享切分，会把其他正在使用GPU的进程干掉

### ISSUE THREAD

**Issue by nicozhang** [Project-HAMi/HAMi#65]
会提示 Lock shrreg timeout 
Owner proc dead
Kick dead proc 
kick 的时候，就会把正在使用GPU 的进程给 kill 掉了

![wecom-temp-86129-a94827c42bbe3e1df114913b03c7508b](https://github.com/4paradigm/k8s-vgpu-scheduler/assets/1912794/46be996e-1d5f-4ab7-a589-0b9b27e3d3ba)
![wecom-temp-147484-ebe181041c6daf1d25fd8a67a00d56ce](https://github.com/4paradigm/k8s-vgpu-scheduler/assets/1912794/184a5285-923f-4c29-8e7e-98d814abc1e6)

**Comment by archlitchi** [comment]
这个应该更新到2.2.14就能解决
