### ISSUE TITLE
CUDA error device kernel image is invalid when using torch with CUDA 11.6

### ISSUE THREAD

**Issue by ltson4121994** [Project-HAMi/HAMi#666]
**Please provide an in-depth description of the question you have**:
We are trying Hami with a pod that have torch installed and whenever we tried to call any function related to cuda it would return device kernel image invalid. We did some quick search and see that this error usualy caused by inconsistency in CUDA version. When I tried to run torch.version.cuda it returns 11.6 but the libvgpu.so is built on CUDA 12.2. Is it expected that libvgpu.so needs to be built on the exact same CUDA version?

**What do you think about this question?**:
I think libvgpu.so should be compatible with previous CUDA version, or maybe it already is but I just misconfig at some step?

**Environment**:
- HAMi version: 2.3.13
- Kubernetes version: 1.28
- Others: torch 1.13 cuda 11.6

**Comment by archlitchi** [comment]
it should run on cuda v11.6 environment. I think there must be some issues in your image. Can you re-submit this job with env "CUDA_DISABLE_CONTROL=true" to see if that error still happens?

**Comment by ltson4121994** [comment]
The error still happens with "CUDA_DISABLE_CONTROL=true", I think the issue might be related to nvidia container runtime. Thanks for your reply.
