### ISSUE TITLE
启用虚拟显存功能后，使用nvidia-smi命令查看算法进程消耗991M显存，整卡消耗1880M

### ISSUE THREAD

**Issue by weight-loss666** [Project-HAMi/HAMi#69]
当我使用k8s-vgpu-scheduler，启用虚拟显存功能后，启动某个算法任务POD，该POD申请虚拟显存2560M。改算法任务可以正常运行，当我使用nvidia-smi命令查看算法进程消耗991M显存，整卡消耗1880M，请问整卡中除了算法进程消耗显存外，剩余的显存（1880-991=889M）是被谁消耗的呢？
![lQLPJyAzgiI_aSrNAaDNArWwHziJnzOM1_0EcBl438CpAA_693_416](https://github.com/4paradigm/k8s-vgpu-scheduler/assets/59427407/3bc3c72c-3dcc-412c-ac2f-40a92005ff59)

**Comment by archlitchi** [comment]
也是被这个任务消耗的，使用虚拟显存之后，确实显示上会存在一些gap，这是正常现象，可能跟nvml的统计机制有关
