### ISSUE TITLE
多卡如何指定资源占用？

### ISSUE THREAD

**Issue by yanghangcnc** [Project-HAMi/HAMi#692]
**Please provide an in-depth description of the question you have**:
如果有三张卡(A,B,C)可以使用，我希望我的任务可以完全占用A卡的GPU资源，占用B卡50%的GPU资源，不占用C卡的GPU资源；我该如何编写这个pod的yaml文件指定资源配额？

**What do you think about this question?**:

**Environment**: ubuntu
- HAMi version: v2.4.1
- Kubernetes version: v1.31
- Others: containerd: v1.7.13

**Comment by archlitchi** [comment]
This feature is not supported in this version, device memory must be the same value or same percentage for all devices allocated

**Comment by yanghangcnc** [comment]
ok
