### ISSUE TITLE
算法任务使用2560M显存无法启动，但启用虚拟显存功能后，算法任务使用2560M虚拟显存可启动

### ISSUE THREAD

**Issue by weight-loss666** [Project-HAMi/HAMi#70]
算法任务使用2560M显存无法启动，但启用虚拟显存功能后，算法任务使用2560M虚拟显存可启动，虚拟显存比物理显存性能更好？

**Comment by archlitchi** [comment]
性能好坏主要看场景，如果用在训练上，可能衰减会比较大，如果用在推理上，基本不会有太大的overhead
