### ISSUE TITLE
scheduler container image

### ISSUE THREAD

**Issue by thien-lm** [Project-HAMi/HAMi#701]
**Please provide an in-depth description of the question you have**:
when i deploy hami on my cluster, i saw this image on scheduler pod:
"registry.cn-hangzhou.aliyuncs.com/google_containers/kube-scheduler:v1.28.13"

i am wondering about how i can build that image.

**What do you think about this question?**:

**Environment**:
- HAMi version: 2.4.1
- Kubernetes version: 1.28.113
- Others:

**Comment by lixd** [comment]
This is a native image of k8s kube-scheduler，you need not to build it.
