### ISSUE TITLE
如何设置节点上GPU type

### ISSUE THREAD

**Issue by christu** [Project-HAMi/HAMi#707]
看example里通过 gpu-type 匹配对应的显卡：
https://github.com/Project-HAMi/HAMi/blob/master/examples/nvidia/specify_card_type_to_use.yaml

apiVersion: v1
kind: Pod
metadata:
  name: gpu-pod
  annotations:
    nvidia.com/use-gputype: "A100,V100" # Specify the card type for this job, use comma to seperate, will launch job on specified card
    #In this example, we want to run this job on A100 or V100
spec:
  containers:
    - name: ubuntu-container
      image: ubuntu:18.04
      command: ["bash", "-c", "sleep 86400"]
      resources:
        limits:
          nvidia.com/gpu: 2 # requesting 2 vGPUs

这里gpu type 需要在节点上单独设定吗？

**Comment by Nimbus318** [comment]
不需要，device-plugin 会把所在节点有什么类型的卡注册到 node 的 annotation 上，供调度器指定显卡调度参考

**Comment by christu** [comment]
> 不需要，device-plugin 会把所在节点有什么类型的卡注册到 node 的 annotation 上，供调度器指定显卡调度参考

请问gpu type 是在node annotation的哪个key上体现的呢？

hami.io/node-nvidia-register 这个key吗？

**Comment by Nimbus318** [comment]
是的

**Comment by christu** [comment]
> 是的

![image](https://github.com/user-attachments/assets/43fa95e6-9e68-4717-88ec-ec28bab1b7f5)
这里指定了使用 NVIDIA-NVIDIA T1000 8GB 这张显卡，但pod还是调度到了另一张显卡上，是什么原因呢？

**Comment by Nimbus318** [comment]
你把 node annotation 贴出来看看

**Comment by Nimbus318** [comment]
你把 node annotation 贴出来看看

**Comment by lixd** [comment]
Type 填错了，可以看下 Node 上的 Annoation，来指定，例如：
```bash
root@j99cloudvm:~# node=j99cloudvm
kubectl get node $node -o jsonpath='{.metadata.annotations.hami\.io/node-nvidia-register}'
GPU-03f69c50-207a-2038-9b45-23cac89cb67d,10,46068,100,NVIDIA-NVIDIA A40,0,true:GPU-1afede84-4e70-2174-49af-f07ebb94d1ae,10,46068,100,NVIDIA-NVIDIA A40,0,true:
```
比如这里我们的 GPU Type 则是：NVIDIA-NVIDIA A40, Pod 的 Annotations 中可以指定完整 Type NVIDIA-NVIDIA A40 或者省略直接写 A40 都可以。

**Comment by christu** [comment]
> 你把 node annotation 贴出来看看

![image](https://github.com/user-attachments/assets/e2b4d2cb-6d30-4f24-ab02-4fbe1ea82d79)

**Comment by christu** [comment]
感谢两位，我更改pod 配置文件后解决了
