### ISSUE TITLE
当我请求创建pod的时候，出现以下错误

### ISSUE THREAD

**Issue by ShiroZhang** [Project-HAMi/HAMi#71]
`  Warning  UnexpectedAdmissionError  10s   kubelet  Allocate failed due to rpc error: code = Unavailable desc = error reading from server: EOF, which is unexpected`

**yaml如下：**
apiVersion: v1
kind: Pod
metadata:
  name: gpu-pod
spec:
  nodeName: node6
  containers:
    - name: ubuntu-container
      image: ubuntu:20.04
      command: ["bash", "-c", "sleep 86400"]
      resources:
        limits:
          nvidia.com/gpu: 4

**节点desc如下：**
Addresses:
  InternalIP:  10.250.2.12
  Hostname:    node5
Capacity:
  cpu:                64
  ephemeral-storage:  228554124Ki
  hugepages-1Gi:      0
  hugepages-2Mi:      0
  memory:             131656372Ki
  nvidia.com/gpu:     16
  pods:               110
Allocatable:
  cpu:                64
  ephemeral-storage:  210635480330
  hugepages-1Gi:      0
  hugepages-2Mi:      0
  memory:             131553972Ki
  nvidia.com/gpu:     16
  pods:               110

**环境如下：**
kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.17", GitCommit:"953be8927218ec8067e1af2641e540238ffd7576", GitTreeState:"clean", BuildDate:"2023-02-22T13:34:27Z", GoVersion:"go1.19.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.0", GitCommit:"ab69524f795c42094a6630298ff53f3c3ebab7f4", GitTreeState:"clean", BuildDate:"2021-12-07T18:09:57Z", GoVersion:"go1.17.3", Compiler:"gc", Platform:"linux/amd64"}

root@storage1:~/volador_3# ldd --version
ldd (Ubuntu GLIBC 2.31-0ubuntu9.9) 2.31
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.

**Comment by archlitchi** [comment]
这个任务必须在集群里面有4卡节点才能正常运行，目前任务所需要的卡数量不能大于集群中卡物理GPU最多的节点所拥有的GPU数量
