### ISSUE TITLE
hami version 2.4.1，pod create error :UnexpectedAdmissionError 

### ISSUE THREAD

**Issue by JING21** [Project-HAMi/HAMi#710]
**What happened**:
创建pod报错
Allocate failed due to rpc error: code = Unknown desc = no binding pod found on node kcs-a800-001-s-c5xxw, which is unexpected

**Anything else we need to know?**:
部署过nvidia-device-plugin,已卸载，kubelet，containerd都已重启，并清理过/var/lib/kubelet/device-plugin目录
hami-device-plugin日志无报错

- The output of `nvidia-smi -a` on your host
![image](https://github.com/user-attachments/assets/f8e0fe2d-e7c4-4f41-9f40-49c6313b19c8)

- The hami-device-plugin container logs
![image](https://github.com/user-attachments/assets/fa31091a-3dc4-4fa5-ad76-7c8951c452d8)

- The hami-scheduler container logs
![image](https://github.com/user-attachments/assets/c6a192be-e9f1-4c33-8cb0-b0c4d521279b)

**Environment**:
- HAMi version: 2.4.1
- nvidia driver or other AI device driver version: 550.54.15
- Kernel version from `uname -a` 4.19.90-2107.6.0.0251.43
- Others: 1.25.7 kubernetes version

**Comment by archlitchi** [comment]
Do you set 'nodeName' or 'privileged:true' in yaml file?

**Comment by JING21** [comment]
> Do you set 'nodeName' or 'privileged:true' in yaml file?
Here is the yaml file 
![image](https://github.com/user-attachments/assets/9815204b-8337-409a-bd40-c2769213c33e)

**Comment by JING21** [comment]
It might be same issue as https://github.com/Project-HAMi/HAMi/issues/693

**Comment by Nimbus318** [comment]
> Here is the yaml file
> ![image](https://private-user-images.githubusercontent.com/31011622/396326811-9815204b-8337-409a-bd40-c2769213c33e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ0Mzg5NzUsIm5iZiI6MTczNDQzODY3NSwicGF0aCI6Ii8zMTAxMTYyMi8zOTYzMjY4MTEtOTgxNTIwNGItODMzNy00MDlhLWJkNDAtYzI3NjkyMTNjMzNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE3VDEyMzExNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRlNWRlMTY5ZWEyZmZlZmNkODNkNTdlMWU5MjFkNmE1N2MyOTFhNzU3YjU3MzgxYWVlMjgyODViYjIxZmY4ZmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.m_o7tp3F_mH7eIzQomoOMZI_kfvRE-0gE3tJygrUI5A)

I noticed this and feel it’s worth a reminder: if the `UnexpectedAdmissionError` described in this issue is resolved, the Pod requesting `nvidia.com/gpu: 10` will still remain Pending. This means it requires ten physical GPUs. For a detailed explanation, you can check the pinned explanation about [vGPU](https://github.com/Project-HAMi/HAMi/issues/646) in the top bar of the issue section. There's also a [Chinese version in the FAQ Draft](https://v6eky86feo.feishu.cn/wiki/ViC8wFcItiCCzjkx2c3cgXMhnwh).

**Comment by JING21** [comment]
I had already got that the request num of gpus should less than actual device on the host. (less than 8) But is the x509 cert problem a common issue?

**Comment by whybeyoung** [comment]
same error.  i saw the log below:
![image](https://github.com/user-attachments/assets/f05f30c3-ddbe-421a-9520-e1b598aa9922)

![image](https://github.com/user-attachments/assets/98477378-436e-4d3d-906d-253e665ba91b)
![image](https://github.com/user-attachments/assets/beecaa7b-1f8d-40a9-9930-bd11739eaa1a)

**Comment by whybeyoung** [comment]
![image](https://github.com/user-attachments/assets/9c91934d-58d9-4639-bbd5-b4c0581f5a7b)

**Comment by archlitchi** [comment]
@whybeyoung what is the output of "nvidia-smi topo -m" on that node?

**Comment by whybeyoung** [comment]
![image](https://github.com/user-attachments/assets/378fe389-933c-45f4-b151-352dcd17347d) @archlitchi

**Comment by whybeyoung** [comment]
i  restart the plugin ，despite that these errors still exists,  the node's Allocatable NodeNumbers recovered, and  the pods can working well.

**Comment by JING21** [comment]
The kube-webhook-certgen image create a self-signed ca  to make cert and key file secret for webhook server. So the server will show x509: certificate signed by unknown authority.
Here is the kube-apiserver log:
![image](https://github.com/user-attachments/assets/5588c151-dbe1-435e-aa3d-ac3a2fd6cec3)

**Comment by warmsnial** [comment]
@JING21 

> The kube-webhook-certgen image create a self-signed ca to make cert and key file secret for webhook server. So the server will show x509: certificate signed by unknown authority. Here is the kube-apiserver log: ![image](https://private-user-images.githubusercontent.com/31011622/397260301-5588c151-dbe1-435e-aa3d-ac3a2fd6cec3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ2ODM4NTMsIm5iZiI6MTczNDY4MzU1MywicGF0aCI6Ii8zMTAxMTYyMi8zOTcyNjAzMDEtNTU4OGMxNTEtZGJlMS00MzVlLWFhM2QtYWMzYTJmZDZjZWMzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIwVDA4MzIzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZiNGNkZGRhMTY1YjQzYzhiODRlMjRiYjkzMjUzNjEwNDQ4MWI2M2JhMTczZTZlYTBlZjVmYzFiMGM0MTcxOTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.rNJKj1BxgcbbKUbk3FoFGduPjXViNJTazi0JvponOco)


请问这个问题怎么解决的呢？同样的证书错误导致UnexpectedAdmissionError

**Comment by huangjiasingle** [comment]
restart device-plugin on the node, the all pod will be error on the node when the pod's container useing gpu do someting.  it's directly leads to hami cannot be used in production environment

**Comment by JING21** [comment]
> @JING21
> 
> > The kube-webhook-certgen image create a self-signed ca to make cert and key file secret for webhook server. So the server will show x509: certificate signed by unknown authority. Here is the kube-apiserver log: ![image](https://private-user-images.githubusercontent.com/31011622/397260301-5588c151-dbe1-435e-aa3d-ac3a2fd6cec3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ2ODM4NTMsIm5iZiI6MTczNDY4MzU1MywicGF0aCI6Ii8zMTAxMTYyMi8zOTcyNjAzMDEtNTU4OGMxNTEtZGJlMS00MzVlLWFhM2QtYWMzYTJmZDZjZWMzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIwVDA4MzIzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZiNGNkZGRhMTY1YjQzYzhiODRlMjRiYjkzMjUzNjEwNDQ4MWI2M2JhMTczZTZlYTBlZjVmYzFiMGM0MTcxOTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.rNJKj1BxgcbbKUbk3FoFGduPjXViNJTazi0JvponOco)
> 
> 请问这个问题怎么解决的呢？同样的证书错误导致UnexpectedAdmissionError
参考https://github.com/Project-HAMi/HAMi/issues/693，手动修改webhook的CA，job patch的CA与实际CA会不一致，不清楚原因

**Comment by mhh12121** [comment]
I finally 'resolved' it through replacing certgen image from `docker.io/jettech/kube-webhook-certgen:v1.5.2` to   `swr.cn-north-4.myhuaweicloud.com/ddn-k8s/registry.k8s.io/ingress-nginx/kube-webhook-certgen:v1.4.4-linuxarm64`;
Env: centos7.6 arm, kernel: 4.18

**Comment by googs1025** [comment]
Do we have a solution?

/reopen

**Comment by googs1025** [comment]
```bash
Events:
  Type     Reason                    Age   From            Message
  ----     ------                    ----  ----            -------
  Normal   Scheduled                 14s   hami-scheduler  Successfully assigned default/gpu-pod to gpu12
  Normal   FilteringSucceed          15s   hami-scheduler  Successfully filtered to following nodes: [gpu12] for default/gpu-pod
  Normal   BindingSucceed            15s   hami-scheduler  Successfully binding node [gpu12] to default/gpu-pod
  Warning  UnexpectedAdmissionError  15s   kubelet         Allocate failed due to rpc error: code = Unknown desc = device number not matched, which is unexpected

```

**Comment by wangkang666-edu** [comment]
是910B3的集群
