### ISSUE TITLE
hami2.4.1部署到k8s集群出现 initialization error: nvml error: driver not loaded: unknown的错误

### ISSUE THREAD

**Issue by jxfruit** [Project-HAMi/HAMi#715]
**Please provide an in-depth description of the question you have**:
如题，hami2.4.1部署到k8s集群之后出现failed to create containerd task: failed to create shim: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: Running hook #0:: error running hook: exit status 1, stdout: , stderr: Auto-detected mode as 'legacy'
nvidia-container-cli: initialization error: nvml error: driver not loaded: unknown

**What do you think about this question?**:
k8s集群主节点上没有GPU，worker节点上是有GPU的，hami-scheduler-bb9b4c544-txdsj这个Pod默认会在主节点上创建，但是这个Pod下面创建的vgpu-scheduler-extender容器会一直报这个加载驱动的错误。请问下我们当前的版本必须要保证所有节点都要有GPU么，如果不是那应该怎么解决呢

**Environment**:
- HAMi version: 2.4.1
- Kubernetes version: 1.22.8
- Others:

**Comment by Nimbus318** [comment]
从报错看，我猜测是 Master 的容器的运行时也被设置成了 nvidia-container-runtime，但是没 GPU 的节点不用配置这个，如果是这个原因，Master 恢复成默认的 runc 应该就行

**Comment by jxfruit** [comment]
> 从报错看，我猜测是 Master 的容器的运行时也被设置成了 nvidia-container-runtime，但是没 GPU 的节点不用配置这个，如果是这个原因，Master 恢复成默认的 runc 应该就行

感谢感谢
