### ISSUE TITLE
HAMI Local Debugging

### ISSUE THREAD

**Issue by elrondwong** [Project-HAMi/HAMi#721]
**Description:**  
Setting up the local debugging environment for HAMI took quite some time. I’ve documented the steps and key points in hopes of helping others who might need it. You can find the details at the link below:  
[HAMI Local Debugging Guide](https://github.com/elrondwong/elrond.wang/blob/master/_posts/2024-12-20-HAMI%E6%9C%AC%E5%9C%B0%E8%B0%83%E8%AF%95.md)

Feel free to comment below if you encounter any issues or have suggestions! 😊

**Comment by Shouren** [comment]
> **Description:** Setting up the local debugging environment for HAMI took quite some time. I’ve documented the steps and key points in hopes of helping others who might need it. You can find the details at the link below: [HAMI Local Debugging Guide](https://github.com/elrondwong/elrond.wang/blob/master/_posts/2024-12-20-HAMI%E6%9C%AC%E5%9C%B0%E8%B0%83%E8%AF%95.md)
> 
> Feel free to comment below if you encounter any issues or have suggestions! 😊

I think it is better to set `EnableServiceLinks` in Pod Spec(For more info, please refer to [Pod](https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/)) to `false` before collecting environment variables.
For example, those environments injected by K8s in your post are not necessary for debugging HAMi locally.
```
...
export OLLAMA_NODEPORT_SERVICE_PORT_11434_TCP_PROTO=tcp
...
export COREDNS_SERVICE_PORT_METRICS=9153
export COREDNS_PORT_53_TCP_PROTO=tcp
export COREDNS_PORT_9153_TCP_PROTO=tcp
...
```
And when collecting environments in a large K8s cluster, there may be thousands of environments which may has side effect for debugging.

**Comment by elrondwong** [comment]
Learned something new! This is really useful.

**Comment by elrondwong** [comment]
> 你简直是天使啊，贡献了好几个在使用过程中遇到的问题，专门记录并分享出来给大家参考！！！
> 
> 给你疯狂手动点赞👍👍👍

项目蛮有意思的，学习一下，有赖指导 🎉
