### ISSUE TITLE
显存scale后，超售部分的显存和内存的消耗关系？

### ISSUE THREAD

**Issue by tktktktktktktktktk** [Project-HAMi/HAMi#76]
尊敬的开发者老师，您好，我使用Tesla V100-SXM2-32GB测试下来，发现显存超售部分需要消耗大约两倍于超售显存的主机内存多一点，请问是符合预期的吗？
请教下显存scaling的原理和CUDA Unified Memory有关吗？

**Comment by archlitchi** [comment]
> 尊敬的开发者老师，您好，我使用Tesla V100-SXM2-32GB测试下来，发现显存超售部分需要消耗大约两倍于超售显存的主机内存多一点，请问是符合预期的吗？ 请教下显存scaling的原理和CUDA Unified Memory有关吗？

是符合的，这个原理上就是通过unified memory实现的
