### ISSUE TITLE
希望支持国产显卡

### ISSUE THREAD

**Issue by liuxin638507** [Project-HAMi/HAMi#78]
部分场景使用国产显卡，华为显卡居多，如300I、310I PRO、 900卡等等，请问是否有这个计划，要是也能虚拟化，更便于调度与管理

**Comment by archlitchi** [comment]
> 部分场景使用国产显卡，华为显卡居多，如300I、310I PRO、 900卡等等，请问是否有这个计划，要是也能虚拟化，更便于调度与管理

我们其实很想把华为的卡加上去，但需要华为那边提供技术支持才行
