### ISSUE TITLE
不同用户视角下看到的显存结果不一致

### ISSUE THREAD

**Issue by zeta65** [Project-HAMi/HAMi#79]
GPU：RTX 3070，显存8G
开启2倍显存超分后创建了一个 Pod，nvidia.com/gpumem 指定为 4096
进入容器内部，使用 root 用户查看显存，结果为 4096M
![img_v2_07cd22b0-30d8-4646-8e0d-3ee58145c52g](https://github.com/4paradigm/k8s-vgpu-scheduler/assets/109952974/4995711d-02da-4c7a-b0ab-d5cc808ab2d3)
新建用户 tom ，查看显存，结果为 8192M
![img_v2_96855cfc-291f-4a44-8db7-bb07549157dg](https://github.com/4paradigm/k8s-vgpu-scheduler/assets/109952974/e29da266-f910-49da-93e9-977856958cff)

**Comment by Lai-JX** [comment]
我遇到的问题是，如果通过ssh连接容器，那么显存的显示结果是错误的，这是因为ssh建立连接时导致环境变量被重置，解决方法见[解决ssh连接docker容器环境变量无效的问题](https://blog.csdn.net/u014681799/article/details/108058788)

我猜测您遇到的问题也是由环境变量引起的
