### ISSUE TITLE
在rancher中创建遇到问题

### ISSUE THREAD

**Issue by evenking1** [Project-HAMi/HAMi#91]
在部署pod的时候，只要设置了GPU就会出现错误“0/3 nodes are available: 3 node unregisterd. preemption: 0/3 nodes are available: 3 No preemption victims found for incoming pod..”这个是什么情况？还有，有没有微信群交流一下的？

**Comment by archlitchi** [comment]
我没有用rancher部署过，不用rancher的话能正常提交么？你可以在contact me里面找到我的联系方式

**Comment by evenking1** [comment]
上面这个问题解决了，但是又遇到个新问题，就是我成功跑起一个vgpu容器后，打算再开一个vgpu容器，它就会报错“Allocate failed due to no healthy devices present; cannot allocate unhealthy devices nvidia.com/gpu, which is unexpected”

**Comment by evenking1** [comment]
好像两个问题是关联的，我显卡是P40，我配置devicePlugin.deviceSplitCount=4，切割4个，但是我在调用的时候只能用一个vgpu，但凡我nvidia.com/gpu: 2或者开启两个nvidia.com/gpu: 1的容器都会不成功

**Comment by archlitchi** [comment]
> 好像两个问题是关联的，我显卡是P40，我配置devicePlugin.deviceSplitCount=4，切割4个，但是我在调用的时候只能用一个vgpu，但凡我nvidia.com/gpu: 2或者开启两个nvidia.com/gpu: 1的容器都会不成功，换句话就是好像vgpu没切割成功

关于第一个问题，任务所能挂载的卡的vgpu数量不能大于实际节点GPU的数量，所以你只有一张卡的话只能是nvidia.com/gpu只能是1
至于为什么不能提交2个nvidia.com/gpu=1的任务，是因为如果你不指定nvidia.com/gpumem的话，当前策略会默认使用整张卡的显存（为了和官方的插件兼容），从而导致第二个任务没有足够的显存资源。你可以在nvidia.com/gpu=1的同时指定nvidia.com/gpumem=5000，这样就能提交2个任务了，你在任务中使用nvidia-smi也能看到显存被限制成了5G

**Comment by evenking1** [comment]
> > 好像两个问题是关联的，我显卡是P40，我配置devicePlugin.deviceSplitCount=4，切割4个，但是我在调用的时候只能用一个vgpu，但凡我nvidia.com/gpu: 2或者开启两个nvidia.com/gpu: 1的容器都会不成功，换句话就是好像vgpu没切割成功
> 
> 关于第一个问题，任务所能挂载的卡的vgpu数量不能大于实际节点GPU的数量，所以你只有一张卡的话nvidia.com/gpu只能是1 至于为什么不能提交2个nvidia.com/gpu=1的任务，是因为如果你不指定nvidia.com/gpumem的话，当前策略会默认使用整张卡的显存（为了和官方的插件兼容），从而导致第二个任务没有足够的显存资源。你可以在nvidia.com/gpu=1的同时指定nvidia.com/gpumem=5000，这样就能提交2个任务了，你在任务中使用nvidia-smi也能看到显存被限制成了5G

我确实能够限制内存大小，但是还是无法启动，我设置了2000的显存大小，所有任务都跑在同一个节点上，就是无法正常启动
![image](https://github.com/4paradigm/k8s-vgpu-scheduler/assets/30852949/b2fa6d09-669e-4f60-9981-9cc4d359c453)

**Comment by archlitchi** [comment]
请问你在装vgpu-scheduler之前有先卸载掉nvidia官方的插件么？

**Comment by evenking1** [comment]
> 请问你在装vgpu-scheduler之前有先卸载掉nvidia官方的插件么？

我看了所有history记录，确定没有安装过英伟达官方插件，我打算重新部署一遍K8S
